from __future__ import annotations

import hashlib
import json
import uuid
from collections import deque
from typing import Any, TYPE_CHECKING

from .completion_models import (
    CompletionClass,
    CompletionEvaluation,
    CompletionExtensionCreate,
    CompletionMapComposeCreate,
    CompletionMapCreate,
    CompletionSystemCreate,
    GenerationStage,
    LocalTranslationStepInput,
    ReadingReceipt,
    ReachWitness,
    TruthReceipt,
)
from .completion_store import CompletionStore, utcnow
from .models import EvidenceStatus, Verdict
from .supernet_models import IntegrationStage, IntegrationStateCreate, ResourceEnvelope

if TYPE_CHECKING:
    from .runtime import ClosureSupernetRuntime


def _stable(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _class_id(members: list[str]) -> str:
    digest = hashlib.sha256(_stable(sorted(members)).encode("utf-8")).hexdigest()[:16]
    return f"completion:{digest}"


def _unique(values: list[str]) -> list[str]:
    return list(dict.fromkeys(str(item) for item in values if str(item)))


class TranslationalCompletionManager:
    """Finite executable chart of NRRF798/799.

    The Lean modules prove the general quotient, truth and universal-property
    theorems. This manager computes the natural completion of one finite submitted
    local-step graph and keeps every quotient equality linked to a finite path.
    """

    def __init__(self, runtime: "ClosureSupernetRuntime", store: CompletionStore):
        self.runtime = runtime
        self.store = store

    def capabilities(self) -> dict[str, Any]:
        return {
            "formal_readings": ["NRRF798", "NRRF799"],
            "canonical_runtime_operation": "integrate",
            "starts_from_bare_local_step_relation": True,
            "translation_relation_assumed_equivalence": False,
            "completion": "equivalence generated by admitted finite local steps",
            "every_identification_requires_finite_local_path": True,
            "local_invariance_iff_global_translationality": True,
            "local_truths_recover_global_completion": True,
            "completion_has_universal_factorization": True,
            "completion_functorial": True,
            "completion_idempotent": True,
            "directed_occurrence_is_not_automatically_admitted_step": True,
            "proof_relevant_paths_retained": True,
            "canonical_representative_selected": False,
            "runtime_is_formal_proof": False,
            "truth_issued": False,
        }

    @staticmethod
    def _graph(
        presentations: list[str], steps: list[LocalTranslationStepInput]
    ) -> dict[str, list[tuple[str, str]]]:
        adjacency = {item: [] for item in presentations}
        for step in steps:
            if not step.admitted_for_completion:
                continue
            adjacency[step.source].append((step.target, step.label))
            adjacency[step.target].append((step.source, step.label))
        for node in adjacency:
            adjacency[node].sort(key=lambda item: (item[0], item[1]))
        return adjacency

    @staticmethod
    def _components(
        presentations: list[str], adjacency: dict[str, list[tuple[str, str]]]
    ) -> tuple[list[list[str]], dict[str, str]]:
        remaining = set(presentations)
        components: list[list[str]] = []
        class_of: dict[str, str] = {}
        for start in presentations:
            if start not in remaining:
                continue
            queue = deque([start])
            remaining.remove(start)
            members: list[str] = []
            while queue:
                node = queue.popleft()
                members.append(node)
                for neighbor, _label in adjacency[node]:
                    if neighbor in remaining:
                        remaining.remove(neighbor)
                        queue.append(neighbor)
            members.sort()
            cid = _class_id(members)
            components.append(members)
            for member in members:
                class_of[member] = cid
        components.sort(key=lambda items: (items[0], len(items)))
        return components, class_of

    @staticmethod
    def _shortest_path(
        source: str,
        target: str,
        adjacency: dict[str, list[tuple[str, str]]],
    ) -> ReachWitness:
        if source == target:
            return ReachWitness(
                source=source,
                target=target,
                related=True,
                path=[source],
                step_labels=[],
                length=0,
                finite_local_lineage=True,
            )
        queue = deque([source])
        previous: dict[str, tuple[str, str] | None] = {source: None}
        while queue:
            node = queue.popleft()
            for neighbor, label in adjacency[node]:
                if neighbor in previous:
                    continue
                previous[neighbor] = (node, label)
                if neighbor == target:
                    queue.clear()
                    break
                queue.append(neighbor)
        if target not in previous:
            return ReachWitness(
                source=source,
                target=target,
                related=False,
                path=[],
                step_labels=[],
                length=None,
                finite_local_lineage=False,
            )
        path = [target]
        labels: list[str] = []
        current = target
        while current != source:
            parent, label = previous[current] or (source, "")
            labels.append(label)
            path.append(parent)
            current = parent
        path.reverse()
        labels.reverse()
        return ReachWitness(
            source=source,
            target=target,
            related=True,
            path=path,
            step_labels=labels,
            length=len(labels),
            finite_local_lineage=True,
        )

    @classmethod
    def evaluate(cls, data: CompletionSystemCreate) -> CompletionEvaluation:
        adjacency = cls._graph(data.presentations, data.steps)
        components, class_of = cls._components(data.presentations, adjacency)

        completion_classes: list[CompletionClass] = []
        all_distances: list[int] = []
        pair_distance: dict[tuple[str, str], int] = {}
        for members in components:
            representative = members[0]
            witnesses = []
            for member in members:
                witness = cls._shortest_path(representative, member, adjacency)
                witnesses.append(witness)
            completion_classes.append(
                CompletionClass(
                    id=class_of[representative],
                    representative=representative,
                    members=members,
                    finite_reach_from_representative=witnesses,
                )
            )
            for source in members:
                for target in members:
                    witness = cls._shortest_path(source, target, adjacency)
                    assert witness.length is not None
                    pair_distance[(source, target)] = witness.length
                    all_distances.append(witness.length)

        max_distance = max(all_distances, default=0)
        generation_stages: list[GenerationStage] = []
        previous_count = 0
        for index in range(max_distance + 1):
            count = sum(int(distance <= index) for distance in pair_distance.values())
            generation_stages.append(
                GenerationStage(
                    index=index,
                    related_ordered_pairs=count,
                    newly_related_ordered_pairs=count - previous_count,
                )
            )
            previous_count = count

        def value_key(value: Any) -> str:
            return _stable(value)

        reading_receipts: list[ReadingReceipt] = []
        for reading in data.readings:
            local = all(
                not step.admitted_for_completion
                or value_key(reading.values[step.source])
                == value_key(reading.values[step.target])
                for step in data.steps
            )
            global_invariant = all(
                len({value_key(reading.values[item]) for item in members}) == 1
                for members in components
            )
            quotient_values: dict[str, Any] | None = None
            if local:
                quotient_values = {
                    class_of[members[0]]: reading.values[members[0]]
                    for members in components
                }
            decides = all(
                (
                    value_key(reading.values[left])
                    == value_key(reading.values[right])
                )
                == (class_of[left] == class_of[right])
                for left in data.presentations
                for right in data.presentations
            )
            range_by_key: dict[str, Any] = {}
            for item in data.presentations:
                range_by_key.setdefault(value_key(reading.values[item]), reading.values[item])
            reading_receipts.append(
                ReadingReceipt(
                    name=reading.name,
                    local_invariant=local,
                    global_invariant=global_invariant,
                    local_iff_global=local == global_invariant,
                    factors_through_completion=local,
                    unique_factorization=local,
                    quotient_values=quotient_values,
                    decides_completion=decides,
                    range_values=list(range_by_key.values()),
                    metadata=reading.metadata,
                )
            )

        truth_receipts: list[TruthReceipt] = []
        for truth in data.truths:
            local = all(
                not step.admitted_for_completion
                or truth.values[step.source] == truth.values[step.target]
                for step in data.steps
            )
            global_invariant = all(
                len({truth.values[item] for item in members}) == 1
                for members in components
            )
            quotient_values = (
                {
                    class_of[members[0]]: truth.values[members[0]]
                    for members in components
                }
                if local
                else None
            )
            truth_receipts.append(
                TruthReceipt(
                    name=truth.name,
                    local_invariant=local,
                    global_invariant=global_invariant,
                    local_iff_global=local == global_invariant,
                    factors_through_completion=local,
                    quotient_values=quotient_values,
                    metadata=truth.metadata,
                )
            )

        canonical_truths = {
            class_of[members[0]]: {
                presentation: class_of[presentation] == class_of[members[0]]
                for presentation in data.presentations
            }
            for members in components
        }
        pushed_equality = all(
            not step.admitted_for_completion
            or class_of[step.source] == class_of[step.target]
            for step in data.steps
        )
        return CompletionEvaluation(
            classes=completion_classes,
            class_of=class_of,
            generation_stages=generation_stages,
            max_finite_witness_length=max_distance,
            every_identification_has_finite_local_path=True,
            no_global_jump=True,
            local_global_reading_equivalent=all(
                item.local_iff_global for item in reading_receipts
            ),
            local_global_truth_equivalent=all(
                item.local_iff_global for item in truth_receipts
            ),
            all_local_truths_recover_completion=True,
            canonical_class_truths=canonical_truths,
            readings=reading_receipts,
            truths=truth_receipts,
            pushed_step_generates_only_equality=pushed_equality,
            completion_closed=pushed_equality,
            completion_idempotent=pushed_equality,
            quotient_map_natural=True,
            universal_factorization_available=True,
            canonical_representative_selected=False,
            truth_issued=False,
        )

    def _source_context(
        self, source_event_id: str | None, source_ids: list[str]
    ) -> tuple[list[str], list[str]]:
        exact_sources = list(source_ids)
        parents: list[str] = []
        if source_event_id is not None:
            event = self.runtime.supernet_store.get_event(source_event_id)
            exact_sources.extend(event["exact_source_ids"])
            parents.append(source_event_id)
        return _unique(exact_sources), parents

    async def create_system(
        self,
        data: CompletionSystemCreate,
        *,
        parent_system_id: str | None = None,
    ) -> dict[str, Any]:
        system_id = str(uuid.uuid4())
        evaluation = self.evaluate(data)
        source_ids, parents = self._source_context(data.source_event_id, data.source_ids)
        if parent_system_id is not None:
            parent = self.store.get_system(parent_system_id)
            parents.append(parent["integration_event_id"])
            source_ids.extend(parent["source_ids"])
            source_ids = _unique(source_ids)

        exact_text = _stable(
            {
                "NRRF798": "full closure through translational truth",
                "NRRF799": "natural translational completion equally global and local",
                "name": data.name,
                "presentations": data.presentations,
                "steps": [item.model_dump(mode="json") for item in data.steps],
                "classes": [item.model_dump(mode="json") for item in evaluation.classes],
                "readings": [item.model_dump(mode="json") for item in evaluation.readings],
                "truths": [item.model_dump(mode="json") for item in evaluation.truths],
            }
        )
        receipt = await self.runtime.integrate_resource(
            ResourceEnvelope(
                exact_text=exact_text,
                authored_by=data.authored_by,
                form_label="natural translational completion",
                language_label="NRRF798/799 finite local-step chart",
                source_id="translational-completion-supernet",
                perspective_id=data.perspective_id,
                problem_id=data.problem_id,
                capabilities=[
                    "generate completion from bare local steps",
                    "retain finite path witnesses",
                    "factor locally invariant readings through completion",
                    "recover closure from translational truths",
                ],
                constraints=[
                    "finite submitted presentation graph",
                    "only admitted steps generate equivalence",
                    "directed occurrences remain distinct from admitted translations",
                    "no canonical representative",
                    "determination does not issue TRUE",
                ],
                relation_hints=[
                    "NRRF798",
                    "NRRF799",
                    "EqvGen",
                    "finite reach",
                    "local global completion",
                    "translational truth",
                ],
                causal_predecessor_ids=_unique(parents),
                parent_event_ids=_unique(parents),
                affected_perspectives=[data.authored_by],
                evidence_status=EvidenceStatus.FORMALLY_PROVED_UNDER_READING,
                adapter_label="completion",
                external_key=f"completion:system:{system_id}",
                metadata={
                    **data.metadata,
                    "system_id": system_id,
                    "parent_system_id": parent_system_id,
                    "formal_readings": ["NRRF798", "NRRF799"],
                    "evaluation": evaluation.model_dump(mode="json"),
                    "source_ids": source_ids,
                    "runtime_is_formal_proof": False,
                    "truth_issued": False,
                },
            )
        )
        row = {
            "id": system_id,
            "occurrence_id": receipt["occurrence_ids"][0],
            "integration_event_id": receipt["event_id"],
            "name": data.name,
            "authored_by": data.authored_by,
            "presentations": data.presentations,
            "steps": [item.model_dump(mode="json") for item in data.steps],
            "readings": [item.model_dump(mode="json") for item in data.readings],
            "truths": [item.model_dump(mode="json") for item in data.truths],
            "source_event_id": data.source_event_id,
            "parent_system_id": parent_system_id,
            "perspective_id": data.perspective_id,
            "problem_id": data.problem_id,
            "source_ids": source_ids,
            "evaluation": evaluation.model_dump(mode="json"),
            "metadata": {
                **data.metadata,
                "canonical_representative_selected": False,
                "runtime_is_formal_proof": False,
                "truth_issued": False,
            },
            "created_at": utcnow(),
        }
        stored = self.store.create_system(row)
        self.runtime.supernet_integrator.determine(
            receipt["event_id"],
            actor_id=data.authored_by,
            rigidity_scope=[
                "generated equivalence classes",
                "finite local path lineage",
                "local/global invariant readings",
                "translational truth quotient",
            ],
            rigidity_receipt={
                "starts_from_bare_step_relation": True,
                "equivalence_assumed": False,
                "every_identification_has_finite_local_path": True,
                "local_global_same_completion": True,
                "all_local_truths_recover_completion": True,
                "completion_closed": evaluation.completion_closed,
                "completion_idempotent": evaluation.completion_idempotent,
                "canonical_representative_selected": False,
                "runtime_is_formal_proof": False,
            },
            determined_form={
                "system_id": system_id,
                "completion_classes": [
                    item.model_dump(mode="json") for item in evaluation.classes
                ],
                "quotient_map": evaluation.class_of,
                "translational_truths": evaluation.canonical_class_truths,
                "canonical_representative": None,
                "canonical_language": None,
            },
            unitary_path_partition={
                "path": [
                    "local step",
                    "finite symmetric reach",
                    "generated equivalence",
                    "natural completion",
                    "translational truth",
                    "return and reopening",
                ],
                "partition": evaluation.class_of,
                "max_finite_witness_length": evaluation.max_finite_witness_length,
            },
            reason=(
                "The finite local-step graph generates one natural completion, "
                "and every quotient identification has a retained finite path"
            ),
        )
        self.runtime.supernet_integrator.transition(
            receipt["event_id"],
            IntegrationStateCreate(
                stage=IntegrationStage.RETURNED,
                verdict=Verdict.OPEN,
                reason=(
                    "The completed local relation returns as successor potential; "
                    "new local translations may reopen and enlarge it"
                ),
                actor_id=data.authored_by,
                returned_resource_ids=[system_id],
                successor_potential=[
                    {
                        "form_type": "translational-completion",
                        "system_id": system_id,
                        "class_count": len(evaluation.classes),
                        "new_local_steps_may_reopen": True,
                    }
                ],
                metadata={
                    "nrrf798": True,
                    "nrrf799": True,
                    "truth_issued": False,
                    "canonical_representative_selected": False,
                },
            ),
        )
        self.projection()
        return self.store.get_system(stored["id"])

    async def extend_system(
        self, system_id: str, data: CompletionExtensionCreate
    ) -> dict[str, Any]:
        parent = self.store.get_system(system_id)
        presentations = list(parent["presentations"])
        for item in data.added_presentations:
            if item not in presentations:
                presentations.append(item)
        known = set(presentations)
        for step in data.added_steps:
            if step.source not in known or step.target not in known:
                raise ValueError("every added step endpoint must exist after extension")

        if data.readings is None:
            inherited_readings = parent["readings"]
            if data.added_presentations and inherited_readings:
                raise ValueError(
                    "extensions adding presentations must submit complete replacement readings"
                )
            readings = inherited_readings
        else:
            readings = [item.model_dump(mode="json") for item in data.readings]
        if data.truths is None:
            inherited_truths = parent["truths"]
            if data.added_presentations and inherited_truths:
                raise ValueError(
                    "extensions adding presentations must submit complete replacement truths"
                )
            truths = inherited_truths
        else:
            truths = [item.model_dump(mode="json") for item in data.truths]

        self.runtime.supernet_integrator.transition(
            parent["integration_event_id"],
            IntegrationStateCreate(
                stage=IntegrationStage.REOPENED,
                verdict=Verdict.OPEN,
                reason="New local translations reopen the prior completion stage",
                actor_id=data.authored_by,
                successor_potential=[
                    {
                        "form_type": "completion-extension",
                        "parent_system_id": system_id,
                        "added_presentations": data.added_presentations,
                        "added_steps": [item.model_dump(mode="json") for item in data.added_steps],
                    }
                ],
                metadata={"truth_issued": False, "historical_completion_retained": True},
            ),
        )
        child = CompletionSystemCreate(
            name=f"{parent['name']} — reopened completion",
            authored_by=data.authored_by,
            presentations=presentations,
            steps=[
                LocalTranslationStepInput.model_validate(item)
                for item in parent["steps"]
            ]
            + data.added_steps,
            readings=readings,
            truths=truths,
            source_event_id=data.source_event_id,
            perspective_id=parent.get("perspective_id"),
            problem_id=parent.get("problem_id"),
            source_ids=_unique(parent["source_ids"] + data.source_ids),
            metadata={
                **parent["metadata"],
                **data.metadata,
                "reopens_system_id": system_id,
            },
        )
        return await self.create_system(child, parent_system_id=system_id)

    def reach_witness(self, system_id: str, source: str, target: str) -> dict[str, Any]:
        system = self.store.get_system(system_id)
        if source not in system["presentations"] or target not in system["presentations"]:
            raise KeyError("source and target must be presentations in the completion system")
        adjacency = self._graph(
            system["presentations"],
            [LocalTranslationStepInput.model_validate(item) for item in system["steps"]],
        )
        return self._shortest_path(source, target, adjacency).model_dump(mode="json")

    async def create_map(self, data: CompletionMapCreate) -> dict[str, Any]:
        source = self.store.get_system(data.source_system_id)
        target = self.store.get_system(data.target_system_id)
        if set(data.mapping) != set(source["presentations"]):
            raise ValueError("mapping must assign exactly every source presentation")
        if any(value not in target["presentations"] for value in data.mapping.values()):
            raise ValueError("every mapped value must be a target presentation")

        source_class = source["evaluation"]["class_of"]
        target_class = target["evaluation"]["class_of"]
        relation_preserving = all(
            not step.get("admitted_for_completion", True)
            or target_class[data.mapping[step["source"]]]
            == target_class[data.mapping[step["target"]]]
            for step in source["steps"]
        )
        induced: dict[str, str] | None = None
        map_mk = False
        if relation_preserving:
            induced = {}
            for presentation in source["presentations"]:
                source_cid = source_class[presentation]
                target_cid = target_class[data.mapping[presentation]]
                existing = induced.get(source_cid)
                if existing is not None and existing != target_cid:
                    relation_preserving = False
                    induced = None
                    break
                induced[source_cid] = target_cid
            map_mk = relation_preserving

        identity = (
            data.source_system_id == data.target_system_id
            and all(data.mapping[item] == item for item in source["presentations"])
        )
        map_id = str(uuid.uuid4())
        source_ids, parents = self._source_context(data.source_event_id, [])
        parents.extend([source["integration_event_id"], target["integration_event_id"]])
        exact_text = _stable(
            {
                "NRRF799": "functorial completion map",
                "source_system_id": data.source_system_id,
                "target_system_id": data.target_system_id,
                "mapping": data.mapping,
                "relation_preserving": relation_preserving,
                "induced_class_map": induced,
            }
        )
        receipt = await self.runtime.integrate_resource(
            ResourceEnvelope(
                exact_text=exact_text,
                authored_by=data.authored_by,
                form_label="translational completion map",
                language_label="NRRF799 functoriality chart",
                source_id="translational-completion-supernet",
                capabilities=["map local steps", "induce quotient map", "commute with quotient maps"],
                constraints=["map is determined only when local steps are preserved"],
                relation_hints=["NRRF799", "map", "map_mk", "functorial completion"],
                causal_predecessor_ids=_unique(parents),
                parent_event_ids=_unique(parents),
                affected_perspectives=[data.authored_by],
                evidence_status=EvidenceStatus.FORMALLY_PROVED_UNDER_READING,
                adapter_label="completion",
                external_key=f"completion:map:{map_id}",
                metadata={
                    **data.metadata,
                    "map_id": map_id,
                    "parent_map_ids": data.parent_map_ids,
                    "relation_preserving": relation_preserving,
                    "truth_issued": False,
                },
            )
        )
        row = {
            "id": map_id,
            "occurrence_id": receipt["occurrence_ids"][0],
            "integration_event_id": receipt["event_id"],
            "source_system_id": data.source_system_id,
            "target_system_id": data.target_system_id,
            "mapping": data.mapping,
            "relation_preserving": relation_preserving,
            "induced_class_map": induced,
            "map_mk_commutes": map_mk,
            "identity_map": identity,
            "parent_map_ids": data.parent_map_ids,
            "authored_by": data.authored_by,
            "source_event_id": data.source_event_id,
            "metadata": {**data.metadata, "truth_issued": False},
            "created_at": utcnow(),
        }
        stored = self.store.create_map(row)
        if relation_preserving:
            self.runtime.supernet_integrator.determine(
                receipt["event_id"],
                actor_id=data.authored_by,
                rigidity_scope=["local-step preservation", "induced quotient map"],
                rigidity_receipt={
                    "relation_preserving": True,
                    "map_mk_commutes": True,
                    "identity_law": identity,
                    "canonical_representative_selected": False,
                },
                determined_form={
                    "map_id": map_id,
                    "induced_class_map": induced,
                    "canonical_representative": None,
                },
                reason="The local-step-preserving map induces one map of natural completions",
            )
        self.runtime.supernet_integrator.transition(
            receipt["event_id"],
            IntegrationStateCreate(
                stage=IntegrationStage.RETURNED,
                verdict=Verdict.OPEN,
                reason="The completion map returns without issuing a truth verdict",
                actor_id=data.authored_by,
                returned_resource_ids=[map_id],
                metadata={"relation_preserving": relation_preserving, "truth_issued": False},
            ),
        )
        self.projection()
        return self.store.get_map(stored["id"])

    async def compose_maps(self, data: CompletionMapComposeCreate) -> dict[str, Any]:
        first = self.store.get_map(data.first_map_id)
        second = self.store.get_map(data.second_map_id)
        if first["target_system_id"] != second["source_system_id"]:
            raise ValueError("first map target must equal second map source")
        composed = {
            source: second["mapping"][middle]
            for source, middle in first["mapping"].items()
        }
        return await self.create_map(
            CompletionMapCreate(
                source_system_id=first["source_system_id"],
                target_system_id=second["target_system_id"],
                mapping=composed,
                authored_by=data.authored_by,
                parent_map_ids=[data.first_map_id, data.second_map_id],
                metadata={**data.metadata, "composition_law": True},
            )
        )

    def projection(self) -> dict[str, Any]:
        systems = self.store.list_systems()
        maps = self.store.list_maps()
        projection = {
            "generated_at": utcnow(),
            "systems": systems,
            "maps": maps,
            "stats": self.store.stats(),
            "source_reverse_index": {
                **{
                    f"completion:{item['id']}": list(item["source_ids"])
                    for item in systems
                },
                **{
                    f"completion-map:{item['id']}": list(
                        self.runtime.supernet_store.get_event(item["integration_event_id"])[
                            "exact_source_ids"
                        ]
                    )
                    for item in maps
                },
            },
            "formal_readings": ["NRRF798", "NRRF799"],
            "canonical_runtime_operation": "integrate",
            "local_global_same_completion": True,
            "every_global_identification_requires_finite_local_lineage": True,
            "truth_issued": False,
        }
        self.store.set_state("completion_field_projection", projection)
        return projection
