from __future__ import annotations

"""Supernet interaction closure derived from observer-observed translation.

The semantic primitive is not equality between two observations and not a fixed
return.  It is a relative interaction carrier:

    returned perspective (observer)
      + source-preserved observed states
      + admissible interaction
      -> translation witness

Returns are witnesses generated by that carrier.  UI/chart/natural-form equality
is checked only afterward as a derived closure consequence.
"""

import hashlib
import json
from typing import Any, Iterable, Mapping

from .closure_continuity import (
    OPEN_STATUS,
    WITNESSED_STATUS,
    ClosureWitness,
    audit_translational_continuity,
    combine_witnesses,
    compatibility_reading_receipt,
    derive_perspective_reading,
)
from .interactive_translation_relation import derive_relative_interactions

PROTOCOL = "SUPERNET-INTERACTION-CLOSURE"
SCHEMA = "closure.supernet/perspective-interaction-relation-v4"


def _stable(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str)


def _digest(prefix: str, value: Any) -> str:
    return f"{prefix}:{hashlib.sha256(_stable(value).encode('utf-8')).hexdigest()[:24]}"


def _unique(values: Iterable[Any]) -> list[str]:
    return list(dict.fromkeys(str(value) for value in values if value is not None and str(value)))


def _natural_form_indexes(
    truth_derivation: Mapping[str, Any],
) -> tuple[dict[str, dict[str, Any]], dict[str, str], list[str]]:
    forms: dict[str, dict[str, Any]] = {}
    form_by_member: dict[str, str] = {}
    conflicts: set[str] = set()
    for raw in truth_derivation.get("natural_forms", []):
        form = dict(raw)
        form_id = str(form.get("id") or "")
        if not form_id:
            continue
        forms[form_id] = form
        for member in _unique(form.get("members", [])):
            previous = form_by_member.get(member)
            if previous is not None and previous != form_id:
                conflicts.add(member)
            else:
                form_by_member[member] = form_id
    return forms, form_by_member, sorted(conflicts)


def derive_interaction_closure(
    *,
    truth_derivation: dict[str, Any],
    nrrf843_ui: dict[str, Any],
    nrrf842_journey: dict[str, Any],
    coordination: dict[str, Any],
    ai_translation: dict[str, Any],
    tokenomic: dict[str, Any],
    visual_network: dict[str, Any],
    black_mirror: dict[str, Any],
    network_return: dict[str, Any],
) -> dict[str, Any]:
    """Derive one interactive translational closure.

    Historical products remain visible as compatibility readings.  They cannot
    select the observer, define an observed relation, gate interaction, or widen
    translational truth.
    """

    truth_id = str(truth_derivation.get("id") or "")
    visual_closure_id = str(truth_derivation.get("visual_truth_closure", {}).get("id") or "")
    ui_id = str(nrrf843_ui.get("id") or "")
    forms, form_by_member, conflicting_form_members = _natural_form_indexes(truth_derivation)
    truth_members = set(form_by_member)

    # 1. Observer is derived from an explicit returned perspective only.
    perspective = derive_perspective_reading(
        nrrf843_ui=nrrf843_ui,
        nrrf842_journey=nrrf842_journey,
        truth_members=truth_members,
    )
    active_perspective = perspective["active_perspective_id"]
    reading = perspective["projection_reading"]

    # 2. Construct observer-observed interactive translation before comparing
    #    any chart/UI/natural-form equality.
    interactive_translation = derive_relative_interactions(
        observer_id=active_perspective,
        projection_reading=reading,
        form_by_member=form_by_member,
        visual_nodes=list(visual_network.get("nodes", [])),
        visual_edges=list(visual_network.get("edges", [])),
        truth_members=truth_members,
        physical_sensor_attached=black_mirror.get("physical_sensor_attached") is True,
    )

    closure_equations_derived = bool(interactive_translation["closure_equations_derived"])
    source_interactions = interactive_translation["interactions"]
    all_witnessed_translations_preserve_closure = all(
        (not row["translation_relation_witnessed"]) or row["closure_preserved_after_translation"]
        for row in source_interactions
    )

    witnesses = [
        ClosureWitness(
            "truth_source_present",
            bool(truth_id and visual_closure_id and forms and not conflicting_form_members),
            "Source closure and conflict-free natural forms are required before a relative translation can be checked.",
            tuple(item for item in (truth_id, visual_closure_id) if item),
        ),
        ClosureWitness(
            "ui_links_to_truth_source",
            bool(
                truth_id
                and visual_closure_id
                and nrrf843_ui.get("closure_derivation_id") == truth_id
                and nrrf843_ui.get("visual_closure_id") == visual_closure_id
            ),
            "The projection must factor through the same source closure.",
            tuple(item for item in (ui_id, truth_id, visual_closure_id) if item),
        ),
        ClosureWitness(
            "observer_return_witnessed",
            bool(perspective["selection_witnessed"]),
            "The observer must be an explicit returned perspective; the runtime may not synthesize self-location.",
            tuple(item for item in (str(active_perspective or ""),) if item),
        ),
        ClosureWitness(
            "observer_observed_translation_total",
            bool(interactive_translation["translation_reading_total"]),
            "The returned observer must relatively read every and only source-preserved observed member.",
            tuple(interactive_translation["truth_member_ids"]),
        ),
        ClosureWitness(
            "closure_equations_derived_from_translation",
            closure_equations_derived,
            "Natural-form equality must arise as the fibre equality induced by observer-observed translation.",
            tuple(interactive_translation["truth_member_ids"]),
        ),
        ClosureWitness(
            "witnessed_translations_preserve_closure",
            all_witnessed_translations_preserve_closure,
            "Every witnessed interaction must preserve the derived natural-form equality; OPEN interactions remain potential.",
            tuple(row["id"] for row in source_interactions),
        ),
    ]
    continuity = combine_witnesses(witnesses)
    unified = continuity["status"] == WITNESSED_STATUS
    checks = {name: bool(receipt["holds"]) for name, receipt in continuity["witnesses"].items()}

    topology_basis: list[dict[str, Any]] = []
    for group in interactive_translation["translation_partition"]:
        natural_forms = {form_by_member.get(member) for member in group}
        topology_basis.append(
            {
                "translation_fibre_members": list(group),
                "natural_form_id": next(iter(natural_forms)) if len(natural_forms) == 1 else None,
                "closure_fixed": len(natural_forms) == 1,
            }
        )

    topology_nodes = [
        {
            "event_id": row["event_id"],
            "state_id": row["state_id"],
            "perspective_id": row["observer_id"],
            "observer_id": row["observer_id"],
            "observed_id": row["observed_id"],
            "display_fibre_id": row["relative_reading"],
            "natural_form_id": form_by_member.get(row["state_id"]),
            "source_preserved": row["source_preserved"],
            "physical_world_return": row["physical_world_return"],
        }
        for row in interactive_translation["nodes"]
    ]

    topology_relations = [
        {
            "id": row["id"],
            "source_state_id": row["observed_source_id"],
            "target_state_id": row["observed_target_id"],
            "observer_id": row["observer_id"],
            "truth_constraint_status": WITNESSED_STATUS if row["closure_preserved_after_translation"] else OPEN_STATUS,
            "translation_relation_witnessed": row["translation_relation_witnessed"],
            "return_witness_id": row["return_witness_id"],
            "return_is_semantic_primitive": False,
            "generates_topological_identification": row["closure_preserved_after_translation"],
            "visible_potential": not row["closure_preserved_after_translation"],
        }
        for row in source_interactions
    ]

    semantic_relations = [
        {
            "source_state_id": row["source_state_id"],
            "target_state_id": row["target_state_id"],
            "observer_id": row["observer_id"],
            "truth_constraint_status": row["truth_constraint_status"],
        }
        for row in topology_relations
    ]

    potentials = [
        {
            "id": row["id"],
            "shared_natural_form_id": (
                form_by_member.get(row["source_state_id"])
                if form_by_member.get(row["source_state_id"]) == form_by_member.get(row["target_state_id"])
                else None
            ),
            "truth_constraint_status": row["truth_constraint_status"],
            "executes_as_equality": row["generates_topological_identification"],
            "remains_connected_potential": True,
        }
        for row in topology_relations
        if row["visible_potential"]
    ]

    relative_readings = {
        name: compatibility_reading_receipt(name, value, closure_derivation_id=truth_id)
        for name, value in {
            "coordination": coordination,
            "ai_translation": ai_translation,
            "tokenomic": tokenomic,
            "network_return": network_return,
        }.items()
    }

    truth_core = {
        "closure_derivation_id": truth_id,
        "visual_closure_id": visual_closure_id,
        "interactive_translation_id": interactive_translation["id"],
        "observer_id": active_perspective,
        "translation_partition": interactive_translation["translation_partition"],
        "natural_form_partition": interactive_translation["natural_form_partition"],
        "witnesses": checks,
        "relations": semantic_relations,
    }
    translational_truth_id = _digest("translational-truth", truth_core)

    body = {
        "protocol": PROTOCOL,
        "schema": SCHEMA,
        "closure_derivation_id": truth_id,
        "visual_closure_id": visual_closure_id,
        "nrrf843_ui_id": ui_id,
        "translational_truth_id": translational_truth_id,
        "status": WITNESSED_STATUS if unified else OPEN_STATUS,
        "supernet_interaction_closed": unified,
        "closed_relation_not_closed_existence": unified,
        "existence_closed": False,
        "dialectic_continuation_status": OPEN_STATUS,
        "one_interaction_surface": unified,
        "semantic_primitive": "OBSERVER_OBSERVED_INTERACTIVE_TRANSLATION",
        "observation_equality_is_primitive": False,
        "chart_equivalence_is_primitive": False,
        "fixed_return_is_primitive": False,
        "interactive_translation": interactive_translation,
        "translational_continuity": continuity,
        "unification_constraint": {
            "status": WITNESSED_STATUS if unified else OPEN_STATUS,
            "checks": checks,
            "all_components_share_one_translational_truth": unified,
            "parallel_truth_runtime_present": False,
            "stored_status_flags_used_as_evidence": False,
            "configuration_authors_truth": False,
        },
        "projection_equivalence": {
            "reading_total": interactive_translation["translation_reading_total"],
            "truth_member_ids": interactive_translation["truth_member_ids"],
            "reading_member_ids": sorted(map(str, reading)),
            "reading_partition": interactive_translation["translation_partition"],
            "natural_form_partition": interactive_translation["natural_form_partition"],
            "conflicting_form_members": conflicting_form_members,
            "partition_equal": closure_equations_derived,
            "derived_from_interactive_translation": True,
            "display_labels_are_semantic_authority": False,
        },
        "perspective_selection": perspective,
        "relative_readings": relative_readings,
        "black_mirror_physical_topology": {
            "status": WITNESSED_STATUS if unified else OPEN_STATUS,
            "active_perspective_id": active_perspective,
            "projection_reading": reading,
            "closure_formula": "translationClosure(o,x,I)=relative equality preserved under observer-observed interaction",
            "topology_basis": topology_basis,
            "nodes": topology_nodes,
            "relations": topology_relations,
            "closure_is_generated_by_projection": False,
            "closure_is_generated_by_interactive_translation": unified,
            "static_external_map": False,
            "physical_law_claimed": False,
        },
        "perspective_digital_potential_gate": {
            "status": WITNESSED_STATUS if unified else OPEN_STATUS,
            "active_perspective_id": active_perspective,
            "potentials": potentials,
            "open_potential_remains_visible": True,
            "open_potential_executes_as_equality": False,
            "independent_gate_layer_present": False,
        },
        "return_relation": {
            "kind": "INTERACTION_GENERATED_SOURCE_PRESERVING_WITNESS",
            "semantic_primitive": False,
            "full_surface": True,
            "reclose_after_return": True,
            "fixed_return_required": False,
            "operation_enum": None,
            "continuation_status": OPEN_STATUS,
            "closed_argument_closes_existence": False,
        },
        "claims": {
            "truth_is_visualization_kernel": False,
            "truth_is_interactive_translation_equivalence": unified,
            "currency_issued": False,
            "legal_binding_claimed": False,
            "physical_law_claimed": False,
            "absolute_truth_issued": False,
        },
    }
    body["continuity_self_audit"] = audit_translational_continuity(body)
    body["id"] = _digest(
        "interaction-closure",
        {
            "translational_truth_id": translational_truth_id,
            "interactive_translation_id": interactive_translation["id"],
            "continuation_status": OPEN_STATUS,
            "continuity_self_audit": body["continuity_self_audit"]["status"],
        },
    )
    return body


__all__ = ["PROTOCOL", "SCHEMA", "derive_interaction_closure"]
