from __future__ import annotations

import hashlib
import json
import math
from typing import Any, Iterable

from .translational_truth_axiometry import derive_closure


def _stable(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _unique(values: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(str(value) for value in values if str(value)))


def _classes(
    states: list[str], admitted_returns: list[dict[str, Any]]
) -> list[list[str]]:
    """Equivalence closure generated by the admitted return edges."""

    parent = {state: state for state in states}

    def find(state: str) -> str:
        while parent[state] != state:
            parent[state] = parent[parent[state]]
            state = parent[state]
        return state

    def union(left: str, right: str) -> None:
        left_root = find(left)
        right_root = find(right)
        if left_root == right_root:
            return
        if left_root < right_root:
            parent[right_root] = left_root
        else:
            parent[left_root] = right_root

    for item in admitted_returns:
        left = str(item.get("source_occurrence") or "")
        right = str(item.get("target_occurrence") or "")
        if left in parent and right in parent:
            union(left, right)

    grouped: dict[str, list[str]] = {}
    for state in states:
        grouped.setdefault(find(state), []).append(state)
    return sorted((sorted(members) for members in grouped.values()), key=lambda row: row[0])


def closure_level_receipt(
    *,
    source_occurrence_ids: Iterable[str],
    relation_receipts: Iterable[dict[str, Any]],
) -> dict[str, Any]:
    """Derive the finite live equality level selected by interaction-time Sense.

    Visual existence comes first.  A cross-return enters the equality-generating
    axiometry only when it has an explicit relative TRUE verdict, compatibility
    witness, and closure-explicit visual equation.  The finite quotient and any
    0↔∞/tan reading are consequences of that derivation, never definitions of
    closure.  OPEN remains visible potential and cannot generate equality.
    """

    relations = [dict(item) for item in relation_receipts]
    states = _unique(
        [
            *source_occurrence_ids,
            *(str(item.get("source_occurrence") or "") for item in relations),
            *(str(item.get("target_occurrence") or "") for item in relations),
        ]
    )
    states.sort()
    relative_truths = [
        {
            "id": item.get("candidate_relation_id") or item.get("id"),
            "source": item.get("source_occurrence"),
            "target": item.get("target_occurrence"),
            "verdict": item.get("verdict", "OPEN"),
            "statement": item.get("relation_type"),
            "provenance": [
                item.get("interpretation_id"),
                item.get("admission_id"),
            ],
            "source_return_ids": item.get("source_return_ids")
            or [item.get("source_occurrence"), item.get("target_occurrence")],
            "visual_equation": item.get("visual_equation"),
            "compatible": item.get("compatible", False),
            "closure_explicit": item.get("closure_explicit"),
        }
        for item in relations
        if item.get("source_occurrence") and item.get("target_occurrence")
    ]
    derivation = derive_closure(
        [
            {
                "id": state,
                "state": {"source_occurrence_id": state},
                "existence_provenance": [f"source-return:{state}"],
            }
            for state in states
        ],
        relative_truths,
    )
    derivation_receipt = derivation.to_dict()
    level_classes = [
        list(members) for members in derivation.equivalence_closure.classes
    ]
    admitted_returns = [
        evaluation
        for evaluation in derivation.truth_evaluations
        if evaluation.closure_admitted
        and evaluation.source != evaluation.target
    ]
    state_count = len(states)
    class_count = len(level_classes)

    degenerate = state_count <= 1
    is_bottom = class_count == state_count
    is_top = state_count > 0 and class_count == 1
    if state_count == 0:
        collapse = None
        angle = None
        tangent: float | str | None = None
        endpoint = "OPEN"
    elif degenerate:
        collapse = None
        angle = None
        tangent = "0≡∞"
        endpoint = "⊥=⊤"
    else:
        endpoint = "⊤" if is_top else "⊥" if is_bottom else "relative"

    level_id = hashlib.sha256(_stable(level_classes).encode("utf-8")).hexdigest()
    quotient = [
        {
            "natural_form": form.id,
            "members": list(form.members),
            "representative_is_not_privileged": True,
            "derived_within_closure": form.derived_within_closure,
            "naturally_admitted": form.admitted,
            "admission_basis": form.admission_basis,
            "existence_provenance": list(form.existence_provenance),
            "source_return_provenance": list(
                form.source_return_provenance
            ),
            "visual_equation_provenance": list(
                form.visual_equation_provenance
            ),
            "compatibility_provenance": list(
                form.compatibility_provenance
            ),
            "closure_explicit_provenance": list(
                form.closure_explicit_provenance
            ),
            "truth_provenance": list(form.truth_provenance),
            "factorization_provenance": list(
                form.factorization_provenance
            ),
        }
        for form in derivation.natural_forms
    ]

    tan_seam_truths = [
        truth
        for truth in derivation.relative_truths
        if truth.verdict.value == "TRUE"
        and truth.meets_visual_existence
        and truth.visual_equation is not None
        and "tan" in truth.visual_equation.equation.lower()
        and (
            "pi/2" in truth.visual_equation.equation.lower()
            or "π/2" in truth.visual_equation.equation.lower()
        )
    ]
    fold_axiometry_witnessed = bool(tan_seam_truths)
    if fold_axiometry_witnessed and state_count > 1:
        collapse = (state_count - class_count) / (state_count - 1)
        angle = collapse * math.pi / 2
        tangent = "∞" if is_top else round(math.tan(angle), 12)
    elif not fold_axiometry_witnessed:
        collapse = None
        angle = None
        tangent = None

    return {
        "formal_reading": "NRRF825",
        "derived_from": (
            "visual existence → translational truth → visual axiometry → "
            "closure-explicit meeting → natural admission"
        ),
        "translational_truth_axiometry": derivation_receipt,
        "level_id": level_id,
        "states": states,
        "state_count": state_count,
        "equality_classes": level_classes,
        "class_count": class_count,
        "endpoint": endpoint,
        "existence_to_admission": {
            "environment": [
                str(item.truth_id)
                for item in admitted_returns
            ],
            "open_returns_excluded_from_equality": True,
            "false_returns_excluded": True,
            "level_env_characterization": (
                "a return is naturally admitted only after compatibility and "
                "closure-explicit visual truth are both witnessed"
            ),
            "current_environment_contained_in_level_env": True,
            "level_env_is_greatest_environment_admitted_at_level": True,
            "truth_form_level_env_equals_level": True,
            "truth_form_surjective_for_finite_levels": True,
            "existence_truth_form": "⊤",
            "existence_closes_to_one_point": True,
            "existence_readings_are_constant": True,
        },
        "truth_closes_level_alone": {
            "natural_forms": quotient,
            "closed_readings_factor_through_truth": True,
            "level_is_complete_invariant_of_closed_readings": True,
            "truth_is_joint_kernel_of_closed_readings": True,
            "identity_reading_closed": is_bottom,
            "faithful_reading_closed": is_bottom,
            "no_direct_or_indirect_state_recovery_above_bottom": not is_bottom,
            "truth_keeps_level_not_environment": True,
            "equivariant_under_state_relabelling": True,
        },
        "projective_fold": {
            "coordinate": (
                "tan((π/2)·collapse)" if fold_axiometry_witnessed else "OPEN"
            ),
            "collapse": collapse,
            "angle_radians": None if angle is None else round(angle, 12),
            "tan_value": tangent,
            "zero": "⊥ · bare equality · faithful readings remain possible",
            "infinity": "⊤ · existence · every closed reading is constant",
            "axiometry_witnessed": fold_axiometry_witnessed,
            "witness_truth_ids": [truth.id for truth in tan_seam_truths],
            "pi_over_two_is_projective_seam": fold_axiometry_witnessed,
            "seam_returns_to_next_sense": fold_axiometry_witnessed,
            "not_a_user_selected_phase": True,
            "defines_closure": False,
            "status": (
                "DERIVED_READING" if fold_axiometry_witnessed else "OPEN_NO_VISUAL_AXIOM"
            ),
        },
        "physical_hypothesis": (
            "OPEN: physical returns must supply their own compatible, "
            "closure-explicit visual truth witnesses"
        ),
        "translational_truth_witnessed": bool(admitted_returns),
        "closure_is_external_limit": False,
        "two_person_E2E": "OPEN",
        "truth_issued": False,
    }
