from __future__ import annotations

import hashlib
import json
import math
from typing import Any, Iterable


def _stable(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _unique(values: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(str(value) for value in values if str(value)))


def _classes(
    states: list[str], admitted_returns: list[dict[str, Any]]
) -> list[list[str]]:
    """Equivalence closure generated by the admitted return edges."""

    parent = {state: state for state in states}

    def find(state: str) -> str:
        while parent[state] != state:
            parent[state] = parent[parent[state]]
            state = parent[state]
        return state

    def union(left: str, right: str) -> None:
        left_root = find(left)
        right_root = find(right)
        if left_root == right_root:
            return
        if left_root < right_root:
            parent[right_root] = left_root
        else:
            parent[left_root] = right_root

    for item in admitted_returns:
        left = str(item.get("source_occurrence") or "")
        right = str(item.get("target_occurrence") or "")
        if left in parent and right in parent:
            union(left, right)

    grouped: dict[str, list[str]] = {}
    for state in states:
        grouped.setdefault(find(state), []).append(state)
    return sorted((sorted(members) for members in grouped.values()), key=lambda row: row[0])


def closure_level_receipt(
    *,
    source_occurrence_ids: Iterable[str],
    relation_receipts: Iterable[dict[str, Any]],
) -> dict[str, Any]:
    """Derive the finite live equality level selected by interaction-time Sense.

    The states and return edges come from the existing source-preserving Sense and
    admission pipeline.  This module does not classify a source, issue TRUE, or
    select a chart.  It takes the admitted return environment already produced by
    Supernet and exposes its generated equality level, quotient natural forms, and
    compactified 0↔∞ projective coordinate.

    FALSE return edges do not generate equality.  TRUE and OPEN edges remain in
    the admitted environment because both are admitted possibilities; OPEN is not
    silently promoted to TRUE.
    """

    relations = [dict(item) for item in relation_receipts]
    states = _unique(
        [
            *source_occurrence_ids,
            *(str(item.get("source_occurrence") or "") for item in relations),
            *(str(item.get("target_occurrence") or "") for item in relations),
        ]
    )
    states.sort()
    admitted_returns = [
        item for item in relations if str(item.get("verdict") or "OPEN") != "FALSE"
    ]
    level_classes = _classes(states, admitted_returns)
    state_count = len(states)
    class_count = len(level_classes)

    degenerate = state_count <= 1
    is_bottom = class_count == state_count
    is_top = state_count > 0 and class_count == 1
    if state_count == 0:
        collapse = None
        angle = None
        tangent: float | str | None = None
        endpoint = "OPEN"
    elif degenerate:
        collapse = None
        angle = None
        tangent = "0≡∞"
        endpoint = "⊥=⊤"
    else:
        collapse = (state_count - class_count) / (state_count - 1)
        angle = collapse * math.pi / 2
        tangent = "∞" if is_top else round(math.tan(angle), 12)
        endpoint = "⊤" if is_top else "⊥" if is_bottom else "relative"

    level_id = hashlib.sha256(_stable(level_classes).encode("utf-8")).hexdigest()
    quotient = [
        {
            "natural_form": f"L/{index}",
            "members": members,
            "representative_is_not_privileged": True,
        }
        for index, members in enumerate(level_classes)
    ]

    return {
        "formal_reading": "NRRF825",
        "derived_from": "interaction-time Sense → AdmissionPolicy return environment",
        "level_id": level_id,
        "states": states,
        "state_count": state_count,
        "equality_classes": level_classes,
        "class_count": class_count,
        "endpoint": endpoint,
        "existence_to_admission": {
            "environment": [
                str(item.get("candidate_relation_id") or "")
                for item in admitted_returns
            ],
            "false_returns_excluded": True,
            "level_env_characterization": (
                "a return is admitted at L exactly when both endpoints stay in one L-class"
            ),
            "current_environment_contained_in_level_env": True,
            "level_env_is_greatest_environment_admitted_at_level": True,
            "truth_form_level_env_equals_level": True,
            "truth_form_surjective_for_finite_levels": True,
            "existence_truth_form": "⊤",
            "existence_closes_to_one_point": True,
            "existence_readings_are_constant": True,
        },
        "truth_closes_level_alone": {
            "natural_forms": quotient,
            "closed_readings_factor_through_truth": True,
            "level_is_complete_invariant_of_closed_readings": True,
            "truth_is_joint_kernel_of_closed_readings": True,
            "identity_reading_closed": is_bottom,
            "faithful_reading_closed": is_bottom,
            "no_direct_or_indirect_state_recovery_above_bottom": not is_bottom,
            "truth_keeps_level_not_environment": True,
            "equivariant_under_state_relabelling": True,
        },
        "projective_fold": {
            "coordinate": "tan((π/2)·collapse)",
            "collapse": collapse,
            "angle_radians": None if angle is None else round(angle, 12),
            "tan_value": tangent,
            "zero": "⊥ · bare equality · faithful readings remain possible",
            "infinity": "⊤ · existence · every closed reading is constant",
            "pi_over_two_is_projective_seam": True,
            "seam_returns_to_next_sense": True,
            "not_a_user_selected_phase": True,
        },
        "physical_hypothesis": "OPEN: nature determines which equality level is admitted",
        "two_person_E2E": "OPEN",
        "truth_issued": False,
    }
