from __future__ import annotations

PUBLIC_NETWORK_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Closure Supernet Living Field</title>
<style>
:root{--bg:#070a10;--panel:#141a27;--panel2:#1b2435;--line:#35425c;--text:#eef3fa;--muted:#aab6c8;--accent:#a8b9ff;--true:#58d493;--open:#e8bf58;--false:#ff747e}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#1a2746,var(--bg) 44%);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}header,main{padding:24px clamp(15px,5vw,66px)}header{border-bottom:1px solid var(--line)}h1{font-size:clamp(32px,5vw,60px);margin:0 0 8px}h2,h3{margin-top:0}.sub{max-width:1100px;color:var(--muted);line-height:1.6}.eq,.panel,.card{background:rgba(20,26,39,.96);border:1px solid var(--line);border-radius:16px;padding:16px}.eq{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;margin-top:17px;overflow:auto}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:16px}.c3{grid-column:span 3}.c4{grid-column:span 4}.c5{grid-column:span 5}.c6{grid-column:span 6}.c7{grid-column:span 7}.c8{grid-column:span 8}.c12{grid-column:span 12}@media(max-width:950px){.c3,.c4,.c5,.c6,.c7,.c8,.c12{grid-column:1/-1}}nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}nav button,.button{width:auto;margin:0;background:var(--panel);border:1px solid var(--line);color:var(--muted);border-radius:999px;padding:9px 14px;cursor:pointer}nav button.active{color:var(--text);border-color:var(--accent)}.tab{display:none}.tab.active{display:block}input,textarea,select,button{width:100%;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px}button{cursor:pointer}label{display:block;color:var(--muted);font-size:13px;margin:10px 0 5px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:650px){.row{grid-template-columns:1fr}}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}@media(max-width:800px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}.metric{background:var(--panel2);border-radius:12px;padding:12px}.metric strong{display:block;font-size:22px}.muted{color:var(--muted);line-height:1.5}.badge{display:inline-block;padding:5px 9px;border-radius:999px;font-weight:750;margin:2px;border:1px solid currentColor}.OPEN{color:var(--open)}.TRUE,.AUTHOR_CONFIRMED{color:var(--true)}.FALSE,.REJECTED{color:var(--false)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:12px}.card{background:var(--panel2)}.card p{white-space:pre-wrap}.small{font-size:12px}.timeline{border-left:2px solid var(--line);padding-left:14px}.event{margin:0 0 12px}.actions{display:flex;gap:7px;flex-wrap:wrap}.actions button{width:auto}.notice{border-left:4px solid var(--accent);background:var(--panel2);padding:12px 14px;border-radius:0 10px 10px 0}.hidden{display:none}pre{white-space:pre-wrap;max-height:480px;overflow:auto;background:#0c111b;padding:12px;border-radius:10px}a{color:var(--accent)}
</style>
</head>
<body>
<header>
<h1>Closure Supernet Living Field</h1>
<div class="sub">A public interaction field where exact authorship remains immutable while perspectives, interpretations, problems, interactions, collective actions, and returned consequences remain continuously reopenable. Solutions are constituted by interactions; no likes, ranks, money, AI output, or terminal result defines the field.</div>
<div class="eq">real problem → note / loop step → interaction / solution → collective action → returned consequence → agentic reintegration → reopened problem</div>
</header>
<main>
<nav>
<button class="active" data-tab="field">Living field</button>
<button data-tab="contribute">Contribute</button>
<button data-tab="problems">Problems & actions</button>
<button data-tab="reintegration">Reintegration</button>
<a class="button" href="/runtime">Runtime console</a>
<a class="button" href="/docs">API</a>
</nav>

<section id="field" class="tab active">
<div class="grid">
<div class="panel c12"><h2>Field state</h2><div id="metrics" class="metrics"></div><p class="muted">These counts describe participation and action, not quality, rank, or moral worth.</p></div>
<div class="panel c7"><h2>Open real problems</h2><div id="problemCards" class="cards"></div></div>
<div class="panel c5"><h2>Recent interaction</h2><div id="timeline" class="timeline"></div></div>
<div class="panel c12"><h2>Current Black Mirror return</h2><div class="notice">The projection is provisional and source-reversible. Selecting or acting on it returns new conditions to the living field.</div><pre id="blackMirror"></pre></div>
</div>
</section>

<section id="contribute" class="tab">
<div class="grid">
<div class="panel c4"><h2>Join the field</h2><label>Display name</label><input id="participantName"><label>Optional public key / authorship reference</label><input id="participantKey"><button onclick="createParticipant()">Create persistent participant</button><p id="participantResult" class="muted"></p></div>
<div class="panel c4"><h2>Open a real problem</h2><label>Author</label><select id="problemAuthor"></select><label>Title</label><input id="problemTitle"><label>Exact problem occurrence</label><textarea id="problemText" rows="5"></textarea><label>Situations presented, one per line</label><textarea id="problemSituations" rows="4"></textarea><button onclick="createProblem()">Open problem</button><p id="problemResult" class="muted"></p></div>
<div class="panel c4"><h2>Add a note / loop step</h2><label>Problem</label><select id="noteProblem"></select><label>Author</label><select id="noteAuthor"></select><label>Exact note</label><textarea id="noteText" rows="7"></textarea><button onclick="addNote()">Interact through note</button><p id="noteResult" class="muted"></p></div>
<div class="panel c6"><h2>Create an interaction / solution</h2><div class="row"><div><label>Problem</label><select id="interactionProblem"></select></div><div><label>Author</label><select id="interactionAuthor"></select></div></div><label>Kind</label><select id="interactionKind"><option>INTERPRETATION</option><option>QUESTION</option><option>TRANSLATION</option><option>ACTION_PROPOSAL</option><option>REINTERPRETATION</option></select><label>Exact interaction</label><textarea id="interactionText" rows="6"></textarea><button onclick="createInteraction()">Constitute solution interaction</button><p id="interactionResult" class="muted"></p></div>
<div class="panel c6"><h2>Propose collective action</h2><div class="row"><div><label>Problem</label><select id="actionProblem"></select></div><div><label>Creator</label><select id="actionAuthor"></select></div></div><label>Action title</label><input id="actionTitle"><label>Exact intent</label><textarea id="actionIntent" rows="5"></textarea><label>Open assumptions, one per line</label><textarea id="actionAssumptions" rows="3"></textarea><button onclick="createAction()">Propose action</button><p id="actionResult" class="muted"></p></div>
</div>
</section>

<section id="problems" class="tab"><div class="grid"><div class="panel c6"><h2>Problems</h2><div id="problemTable"></div></div><div class="panel c6"><h2>Collective actions</h2><div id="actionCards" class="cards"></div></div><div class="panel c12"><h2>Return a consequence</h2><div class="row"><div><label>Action</label><select id="returnAction"></select></div><div><label>Author</label><select id="returnAuthor"></select></div></div><label>Exact returned consequence</label><textarea id="returnText" rows="5"></textarea><label>Affected perspective IDs, comma separated</label><input id="returnAffected"><button onclick="addReturn()">Return consequence and reopen</button><p id="returnResult" class="muted"></p></div></div></section>

<section id="reintegration" class="tab"><div class="grid"><div class="panel c8"><h2>Agentic closure-learning reintegration</h2><p class="muted">Agents may propose how returned consequences re-enter a problem. They cannot autonomously declare global truth or erase either source.</p><div id="reintegrationCards" class="cards"></div></div><div class="panel c4"><h2>Reintegration controls</h2><label>Decision author</label><select id="decisionAuthor"></select><button onclick="runReintegration()">Run reintegration now</button><p class="muted">Author/community decisions remain versioned. OPEN is preserved when affected perspectives or interpretation are incomplete.</p></div></div></section>
</main>
<script>
let FIELD={participants:[],problems:[],interactions:[],actions:[],returns:[],reintegration:[],stats:{},black_mirror:{}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function req(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
function lines(id){return document.getElementById(id).value.split('\n').map(x=>x.trim()).filter(Boolean)}
function csv(id){return document.getElementById(id).value.split(',').map(x=>x.trim()).filter(Boolean)}
function metric(n,v){return `<div class="metric"><span class="muted">${esc(n)}</span><strong>${esc(v)}</strong></div>`}
function options(items,label){return items.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('')}
function setSelects(){const po=options(FIELD.participants,x=>x.display_name);['problemAuthor','noteAuthor','interactionAuthor','actionAuthor','returnAuthor','decisionAuthor'].forEach(id=>document.getElementById(id).innerHTML=po);const probs=options(FIELD.problems,x=>`${x.title} · ${x.current_state}`);['noteProblem','interactionProblem','actionProblem'].forEach(id=>document.getElementById(id).innerHTML=probs);document.getElementById('returnAction').innerHTML=options(FIELD.actions,x=>`${x.title} · ${x.current_state}`)}
function render(){const s=FIELD.stats||{};document.getElementById('metrics').innerHTML=metric('participants',s.participants||0)+metric('real problems',s.problems||0)+metric('interactions / solutions',s.interactions||0)+metric('collective actions',s.actions||0)+metric('returned consequences',s.returns||0)+metric('OPEN reintegration',s.open_reintegration||0)+metric('rankings',s.quantity_quality_rankings||0)+metric('nonterminal',s.nonterminal);
 document.getElementById('problemCards').innerHTML=FIELD.problems.length?FIELD.problems.map(p=>`<article class="card"><span class="badge ${esc(p.current_state==='LOCALLY_SETTLED'?'TRUE':'OPEN')}">${esc(p.current_state)}</span><h3>${esc(p.title)}</h3><p>${esc((p.situations||[]).join('\n'))}</p><div class="small muted">source ${esc(p.occurrence_id)} · author ${esc(p.created_by)}</div></article>`).join(''):'<p class="muted">No problem has been opened yet.</p>';
 const events=[...FIELD.interactions.map(x=>({t:x.created_at,k:x.kind,text:x.metadata?.note_is_loop_step?'note / loop step':'interaction / solution',id:x.id})),...FIELD.returns.map(x=>({t:x.created_at,k:'RETURN',text:'returned consequence',id:x.id}))].sort((a,b)=>String(b.t).localeCompare(String(a.t))).slice(0,16);document.getElementById('timeline').innerHTML=events.length?events.map(x=>`<div class="event"><span class="badge OPEN">${esc(x.k)}</span><div>${esc(x.text)}</div><div class="small muted">${esc(x.t)} · ${esc(x.id)}</div></div>`).join(''):'<p class="muted">No interactions yet.</p>';
 document.getElementById('blackMirror').textContent=JSON.stringify(FIELD.black_mirror,null,2);
 document.getElementById('problemTable').innerHTML=FIELD.problems.map(p=>`<article class="card"><h3>${esc(p.title)}</h3><span class="badge OPEN">${esc(p.current_state)}</span><p class="muted">${esc(p.language_label||'relative language open')}</p><div class="small">${FIELD.interactions.filter(x=>x.from_problem_id===p.id||x.to_problem_id===p.id).length} interactions · ${FIELD.actions.filter(x=>x.problem_id===p.id).length} actions</div></article>`).join('');
 document.getElementById('actionCards').innerHTML=FIELD.actions.length?FIELD.actions.map(a=>`<article class="card"><span class="badge OPEN">${esc(a.current_state)}</span><h3>${esc(a.title)}</h3><p>${esc((a.open_assumptions||[]).join('\n'))}</p><div class="small muted">${FIELD.returns.filter(x=>x.action_id===a.id).length} returned consequences</div></article>`).join(''):'<p class="muted">No collective action proposed.</p>';
 document.getElementById('reintegrationCards').innerHTML=FIELD.reintegration.length?FIELD.reintegration.map(r=>`<article class="card"><span class="badge ${esc(r.current_status)}">${esc(r.current_status)}</span><h3>${esc(r.proposal_text)}</h3><p><strong>Preserved</strong><br>${esc((r.preserved||[]).join('\n'))}</p><p><strong>Changed</strong><br>${esc((r.changed||[]).join('\n'))}</p><p><strong>OPEN</strong><br>${esc((r.open_questions||[]).join('\n'))}</p>${r.current_status==='OPEN'?`<div class="actions"><button onclick="decide('${esc(r.id)}','AUTHOR_CONFIRMED')">Confirm relative reintegration</button><button onclick="decide('${esc(r.id)}','REJECTED')">Reject translation</button></div>`:''}</article>`).join(''):'<p class="muted">No returned consequence awaits reintegration.</p>';setSelects()}
async function refresh(){FIELD=await req('/network/field');render()}
async function createParticipant(){try{const r=await req('/network/participants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:document.getElementById('participantName').value,public_key:document.getElementById('participantKey').value||null})});document.getElementById('participantResult').textContent=`Persistent participant ${r.id}`;await refresh()}catch(e){document.getElementById('participantResult').textContent=e.message}}
async function createProblem(){try{const r=await req('/network/problems',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:document.getElementById('problemTitle').value,exact_text:document.getElementById('problemText').value,situations:lines('problemSituations'),created_by:document.getElementById('problemAuthor').value})});document.getElementById('problemResult').textContent=`Opened real problem ${r.id}`;await refresh()}catch(e){document.getElementById('problemResult').textContent=e.message}}
async function addNote(){try{const r=await req(`/network/problems/${document.getElementById('noteProblem').value}/notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({author_id:document.getElementById('noteAuthor').value,exact_text:document.getElementById('noteText').value})});document.getElementById('noteResult').textContent=`Note became interaction ${r.interaction.id}`;await refresh()}catch(e){document.getElementById('noteResult').textContent=e.message}}
async function createInteraction(){try{const r=await req('/network/interactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_problem_id:document.getElementById('interactionProblem').value,author_id:document.getElementById('interactionAuthor').value,kind:document.getElementById('interactionKind').value,exact_text:document.getElementById('interactionText').value})});document.getElementById('interactionResult').textContent=`Solution receipt ${r.solution_receipt_id}`;await refresh()}catch(e){document.getElementById('interactionResult').textContent=e.message}}
async function createAction(){try{const author=document.getElementById('actionAuthor').value;const r=await req('/network/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({problem_id:document.getElementById('actionProblem').value,title:document.getElementById('actionTitle').value,exact_intent:document.getElementById('actionIntent').value,created_by:author,participant_ids:[author],open_assumptions:lines('actionAssumptions')})});document.getElementById('actionResult').textContent=`Collective action ${r.id}`;await refresh()}catch(e){document.getElementById('actionResult').textContent=e.message}}
async function addReturn(){try{const r=await req(`/network/actions/${document.getElementById('returnAction').value}/returns`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({exact_text:document.getElementById('returnText').value,authored_by:document.getElementById('returnAuthor').value,affected_perspectives:csv('returnAffected')})});document.getElementById('returnResult').textContent=`Returned consequence ${r.id}`;await req('/network/reintegrate',{method:'POST'});await refresh()}catch(e){document.getElementById('returnResult').textContent=e.message}}
async function runReintegration(){await req('/network/reintegrate',{method:'POST'});await refresh()}
async function decide(id,status){const author=document.getElementById('decisionAuthor').value;const reason=prompt('Reason for this relative decision');if(!reason)return;await req(`/network/reintegration/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reason,author_id:author})});await req('/runtime/cycle',{method:'POST'});await refresh()}
document.querySelectorAll('nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}));setInterval(refresh,4000);refresh();
</script>
</body></html>'''
