from __future__ import annotations

RESOURCE_NETWORK_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Closure Supernet · Live Resource Continuum</title>
<style>
:root{--bg:#070b12;--panel:#131b29;--panel2:#1a2638;--line:#36465f;--text:#eff5ff;--muted:#a9b8cc;--accent:#a9c3ff;--open:#e8bf58;--true:#5bd795;--false:#ff7a82}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#233a60,var(--bg) 42%);color:var(--text);font-family:Inter,system-ui,sans-serif}header,main{padding:24px clamp(16px,5vw,70px)}header{border-bottom:1px solid var(--line)}h1{font-size:clamp(32px,5vw,62px);margin:0 0 10px}.sub{max-width:1050px;color:var(--muted);line-height:1.6}.eq,.panel,.card{background:rgba(19,27,41,.96);border:1px solid var(--line);border-radius:16px;padding:16px}.eq{font-family:ui-monospace,monospace;margin-top:16px;overflow:auto}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:15px}.c4{grid-column:span 4}.c6{grid-column:span 6}.c8{grid-column:span 8}.c12{grid-column:span 12}@media(max-width:900px){.c4,.c6,.c8,.c12{grid-column:1/-1}}input,textarea,select,button{width:100%;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px}button{cursor:pointer}label{display:block;color:var(--muted);font-size:13px;margin:10px 0 5px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:12px}.card{background:var(--panel2)}.badge{display:inline-block;border:1px solid currentColor;border-radius:999px;padding:4px 9px;font-weight:750;margin:2px}.OPEN{color:var(--open)}.TRUE{color:var(--true)}.FALSE{color:var(--false)}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:9px}.metric{background:var(--panel2);padding:12px;border-radius:12px}.metric strong{display:block;font-size:22px}.muted{color:var(--muted);line-height:1.5}.notice{border-left:4px solid var(--accent);padding:12px;background:var(--panel2)}a{color:var(--accent)}pre{white-space:pre-wrap;max-height:520px;overflow:auto;background:#0b111b;padding:12px;border-radius:10px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:650px){.row{grid-template-columns:1fr}}</style></head>
<body><header><h1>Live Self-Reintegrating Resource Continuum</h1><div class="sub">Resources remain author-defined relative forms. Active engagement generates returns and translations. Protocol receipts record transport but do not create truth. No finite resource taxonomy or canonical external language is imposed.</div><div class="eq">resource form → engagement → returned form → OPEN translation → relative admission → natural component → further engagement</div></header>
<main><div class="grid">
<div class="panel c12"><div class="notice"><strong>Closure is translational truth, not this protocol.</strong> The protocol preserves sources, histories, delivery order and translation witnesses. Natural unity is generated only by admitted translations.</div><p><a href="/">Living field</a> · <a href="/reopening">Iterated reopening</a> · <a href="/runtime">Runtime</a> · <a href="/docs">API</a></p></div>
<div class="panel c12"><h2>Continuum state</h2><div id="metrics" class="metrics"></div><button onclick="integrate()">Integrate current live stage</button><p id="integrateResult" class="muted"></p></div>
<div class="panel c4"><h2>Create an open resource form</h2><label>Author</label><select id="resourceAuthor"></select><label>Form label (open, not registered)</label><input id="formLabel" placeholder="lesson, compute, commitment, material, story…"><label>Language/frame label (optional)</label><input id="languageLabel"><label>Exact resource occurrence</label><textarea id="resourceText" rows="6"></textarea><button onclick="createResource()">Create resource</button><p id="resourceResult" class="muted"></p></div>
<div class="panel c4"><h2>Engage a resource</h2><label>Resource</label><select id="engageResource"></select><label>Actor</label><select id="engageActor"></select><label>Engagement label (open)</label><input id="engagementLabel" placeholder="study, contribute, transform, coordinate…"><label>Exact engagement</label><textarea id="engagementText" rows="6"></textarea><button onclick="engage()">Engage</button><p id="engagementResult" class="muted"></p></div>
<div class="panel c4"><h2>Return a transformed resource</h2><label>Engagement</label><select id="returnEngagement"></select><label>Author</label><select id="returnAuthor"></select><label>Returned form label</label><input id="returnForm"><label>Exact returned resource</label><textarea id="returnText" rows="6"></textarea><button onclick="returnResource()">Return and queue reintegration</button><button onclick="reintegrate()">Run self-reintegration</button><p id="returnResult" class="muted"></p></div>
<div class="panel c6"><h2>Propose a translation</h2><div class="row"><div><label>Source resource</label><select id="translationSource"></select></div><div><label>Target resource</label><select id="translationTarget"></select></div></div><label>Author</label><select id="translationAuthor"></select><label>Relation label</label><input id="relationLabel" placeholder="reads as, supports, refines, returns through…"><label>Exact translation witness</label><textarea id="translationText" rows="5"></textarea><button onclick="translate()">Propose OPEN translation</button><p id="translationResult" class="muted"></p></div>
<div class="panel c6"><h2>Natural components</h2><div id="components" class="cards"></div></div>
<div class="panel c12"><h2>Resources</h2><div id="resources" class="cards"></div></div>
<div class="panel c12"><h2>Translations</h2><div id="translations" class="cards"></div></div>
<div class="panel c12"><h2>Current live stage</h2><pre id="stage"></pre></div>
</div></main>
<script>
let FIELD={resources:[],engagements:[],translations:[],returns:[],reintegrations:[],stats:{},current_stage:null};let PEOPLE=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function req(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error(await r.text());return r.json()}function metric(k,v){return `<div class="metric"><span class="muted">${esc(k)}</span><strong>${esc(v)}</strong></div>`}function opts(items,label){return items.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('')}
function setSelects(){const p=opts(PEOPLE,x=>x.display_name);['resourceAuthor','engageActor','returnAuthor','translationAuthor'].forEach(id=>document.getElementById(id).innerHTML=p);const r=opts(FIELD.resources,x=>`${x.form_label} · ${x.id.slice(0,8)}`);['engageResource','translationSource','translationTarget'].forEach(id=>document.getElementById(id).innerHTML=r);document.getElementById('returnEngagement').innerHTML=opts(FIELD.engagements,x=>`${x.engagement_label} · ${x.id.slice(0,8)}`)}
function render(){const s=FIELD.stats||{};document.getElementById('metrics').innerHTML=['resources','engagements','translations','returns','pending_reintegrations','stages','natural_components'].map(k=>metric(k,s[k]??0)).join('')+metric('finite registry',s.finite_resource_registry)+metric('canonical language',s.canonical_language_selected)+metric('live=batch',s.live_limit_matches_current_batch);document.getElementById('resources').innerHTML=FIELD.resources.length?FIELD.resources.map(r=>`<article class="card"><span class="badge OPEN">${esc(r.form_label)}</span><h3>${esc(r.language_label||'language remains relative')}</h3><p class="muted">${esc(r.metadata?.return_is_new_resource_form?'returned and reopenable':'source-preserved form')}</p><div class="muted">${esc(r.id)}</div></article>`).join(''):'<p class="muted">No resources yet.</p>';document.getElementById('translations').innerHTML=FIELD.translations.length?FIELD.translations.map(t=>`<article class="card"><span class="badge ${esc(t.current_verdict)}">${esc(t.current_verdict)}</span><h3>${esc(t.relation_label)}</h3><p>${esc(t.source_frame)} → ${esc(t.target_frame)}</p><p class="muted">protocol verdict: ${esc(t.protocol_verdict)} · truth remains separately admitted</p>${t.current_verdict==='OPEN'?`<button onclick="decide('${esc(t.id)}','TRUE')">Admit relatively</button><button onclick="decide('${esc(t.id)}','FALSE')">Reject</button>`:''}</article>`).join(''):'<p class="muted">No translations yet.</p>';const comps=FIELD.current_stage?.natural_components||[];document.getElementById('components').innerHTML=comps.length?comps.map(c=>`<article class="card"><h3>${esc(c.id)}</h3><p>${esc((c.form_labels||[]).join(' ↔ '))}</p><p class="muted">languages: ${esc((c.language_labels||[]).join(', ')||'none selected')}<br>canonical form: none<br>canonical language: none</p></article>`).join(''):'<p class="muted">Integrate a stage to display the current natural components.</p>';document.getElementById('stage').textContent=JSON.stringify(FIELD.current_stage,null,2);setSelects()}
async function refresh(){[FIELD,PEOPLE]=await Promise.all([req('/network/resource-field'),req('/network/participants')]);render()}
async function createResource(){try{const r=await req('/network/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({exact_text:resourceText.value,created_by:resourceAuthor.value,form_label:formLabel.value,language_label:languageLabel.value||null})});resourceResult.textContent=`created ${r.id}`;await refresh()}catch(e){resourceResult.textContent=e.message}}
async function engage(){try{const r=await req('/network/resource-engagements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource_id:engageResource.value,actor_id:engageActor.value,exact_text:engagementText.value,engagement_label:engagementLabel.value})});engagementResult.textContent=`engagement ${r.id}`;await refresh()}catch(e){engagementResult.textContent=e.message}}
async function returnResource(){try{const r=await req('/network/resource-returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({engagement_id:returnEngagement.value,exact_text:returnText.value,authored_by:returnAuthor.value,form_label:returnForm.value})});returnResult.textContent=`returned ${r.returned_resource_id}`;await refresh()}catch(e){returnResult.textContent=e.message}}
async function reintegrate(){try{const r=await req('/network/resource-reintegrate',{method:'POST'});returnResult.textContent=`reintegrated ${r.reintegrated}`;await refresh()}catch(e){returnResult.textContent=e.message}}
async function translate(){try{const r=await req('/network/resource-translations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_resource_id:translationSource.value,target_resource_id:translationTarget.value,authored_by:translationAuthor.value,exact_text:translationText.value,relation_label:relationLabel.value,source_frame:'source participant frame',target_frame:'target participant frame'})});translationResult.textContent=`OPEN translation ${r.id}`;await refresh()}catch(e){translationResult.textContent=e.message}}
async function decide(id,verdict){const who=translationAuthor.value||PEOPLE[0]?.id;await req(`/network/resource-translations/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verdict,reason:`participant-relative ${verdict.toLowerCase()} decision`,decided_by:who})});await integrate()}
async function integrate(){try{const r=await req('/network/resource-live/integrate',{method:'POST'});integrateResult.textContent=`stage ${r.stage.stage_index} · ${r.created_new?'new':'unchanged'}`;await refresh()}catch(e){integrateResult.textContent=e.message}}
refresh();setInterval(refresh,5000);
</script></body></html>'''
