TRADING_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Closure Supernet — Classical Trading Lens</title>
<style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;--bg:#071018;--panel:#0d1823;--line:#26384b;--text:#e8f0f7;--muted:#8ea0b2;--open:#d9ad4f;--good:#52c58d;--bad:#ef7180}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#16283b,#071018 48%);color:var(--text)}header{position:sticky;top:0;z-index:3;padding:16px 22px;border-bottom:1px solid var(--line);background:#071018e8;backdrop-filter:blur(14px);display:flex;justify-content:space-between;align-items:center}h1{font-size:18px;margin:0}header p{margin:4px 0 0;font-size:11px;color:var(--muted)}a{color:#a9d3ff}.wrap{display:grid;grid-template-columns:360px 1fr;min-height:calc(100vh - 72px)}aside{padding:18px;border-right:1px solid var(--line);background:#09131d}.main{padding:18px}.card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:14px;margin-bottom:14px}.card h2{font-size:13px;margin:0 0 10px;text-transform:uppercase;letter-spacing:.08em;color:#a8b8c8}.note{font-size:11px;line-height:1.5;color:var(--muted)}label{display:block;font-size:10px;color:var(--muted);margin:8px 0 4px}input,select,button,textarea{font:inherit;color:inherit}input,select,textarea{width:100%;padding:8px;border-radius:8px;border:1px solid #31465c;background:#071019}button{margin-top:10px;padding:9px 11px;border-radius:9px;border:1px solid #c8d7e5;background:#e7eef5;color:#081019;font-weight:700;cursor:pointer}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.stat{border:1px solid var(--line);border-radius:10px;padding:10px;background:#08121c}.stat strong{display:block;font-size:20px}.stat span{font-size:9px;color:var(--muted)}table{width:100%;border-collapse:collapse;font-size:11px}th,td{text-align:left;padding:8px;border-bottom:1px solid #213244}th{color:#91a4b7}.OPEN{color:var(--open)}.TRUE{color:var(--good)}.FALSE{color:var(--bad)}code{font-family:ui-monospace,SFMono-Regular,monospace}.badge{display:inline-block;border:1px solid #3a5067;border-radius:999px;padding:3px 7px;font-size:9px;color:#aac0d3;margin:2px}.error{color:#ff9ba6}.ok{color:#7be3aa}@media(max-width:900px){.wrap{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid var(--line)}.stats{grid-template-columns:1fr 1fr}}
</style>
</head>
<body>
<header><div><h1>Classical Trading Lens · NRRF780</h1><p>Six local layers → inf cost → value-flow return · simulation only · no broker execution</p></div><nav><a href="/">Supernet</a> · <a href="/docs">API</a></nav></header>
<div class="wrap"><aside>
<div class="card"><h2>Integrate transaction</h2><form id="txForm"><label>Symbol</label><input id="symbol" value="DEMO"><div class="row"><div><label>Signed size</label><input id="size" type="number" step="any" value="1"></div><div><label>Execution</label><select id="mode"><option>SELECTOR_QUOTE</option><option>EXPLICIT</option></select></div></div><div class="row"><div><label>Bid</label><input id="bid" type="number" step="any" value="99"></div><div><label>Ask</label><input id="ask" type="number" step="any" value="101"></div></div><div class="row"><div><label>Fill (explicit only)</label><input id="fill" type="number" step="any"></div><div><label>Mark</label><input id="mark" type="number" step="any" value="100"></div></div><div class="row"><div><label>Fee</label><input id="fee" type="number" step="any" value="0"></div><div><label>Author</label><input id="author" value="participant"></div></div><button type="submit">Integrate and evaluate</button></form><p id="message" class="note"></p></div>
<div class="card"><h2>Selector relation</h2><p class="note"><code>BUY → ASK</code> and <code>SELL → BID</code> are treated as a rigid execution relation. The determined fill remains OPEN and does not issue TRUE.</p></div>
<div class="card"><h2>Boundary</h2><span class="badge">simulation only</span><span class="badge">no brokerage</span><span class="badge">no order submission</span><span class="badge">not financial advice</span></div>
</aside><main class="main">
<div class="card"><h2>Field</h2><div class="stats" id="stats"></div></div>
<div class="card"><h2>Transactions</h2><table><thead><tr><th>Symbol</th><th>Side/size</th><th>Bid / Ask / Fill / Mark</th><th>Cost</th><th>Net</th><th>Identity</th></tr></thead><tbody id="transactions"></tbody></table></div>
<div class="card"><h2>NRRF780 readings</h2><div id="readings" class="note"></div></div>
</main></div>
<script>
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await fetch('/network/trading/field'); const f=await r.json(); const s=f.stats||{}; $('stats').innerHTML=['transactions','systems','circuits','pnl'].map(k=>`<div class="stat"><strong>${s[k]||0}</strong><span>${k}</span></div>`).join(''); $('transactions').innerHTML=(f.transactions||[]).map(t=>{const e=t.evaluation;return `<tr><td>${esc(t.symbol)}</td><td>${esc(e.side)} ${esc(t.signed_size)}</td><td>${esc(t.bid)} / ${esc(t.ask)} / ${esc(t.fill)} / ${esc(t.mark)}</td><td>${esc(e.inf_cost)}</td><td>${esc(e.net_flow)}</td><td class="${e.net_eq_neg_cost?'ok':'error'}">${e.net_eq_neg_cost?'net = −cost':'residual '+esc(e.identity_residual)}</td></tr>`}).join('')||'<tr><td colspan="6" class="note">No trading forms yet.</td></tr>'; $('readings').innerHTML=`<p><b>Local prices:</b> bid, ask, fill, mark. <b>Inf cost:</b> fee + signed-size × (fill − mark). <b>Value flow:</b> signed-size × (mark − fill) − fee = −cost.</p><p>Shift invariance, numéraire covariance, exact-circuit friction, price holonomy, constant-position P&amp;L, and rigid execution-selection endpoints are available through the API.</p>`}
$('mode').onchange=()=>{$('fill').disabled=$('mode').value==='SELECTOR_QUOTE'}; $('mode').onchange();
$('txForm').onsubmit=async e=>{e.preventDefault();$('message').textContent='integrating…';const mode=$('mode').value;const body={symbol:$('symbol').value,signed_size:$('size').value,bid:$('bid').value,ask:$('ask').value,mark:$('mark').value,fee:$('fee').value,execution_mode:mode,authored_by:$('author').value};if(mode==='EXPLICIT')body.fill=$('fill').value;const r=await fetch('/network/trading/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok){$('message').textContent=p.detail||'failed';$('message').className='note error';return}$('message').textContent=`integrated ${p.id}; net ${p.evaluation.net_flow}, cost ${p.evaluation.inf_cost}`;$('message').className='note ok';await load()};
load();setInterval(load,5000);
</script></body></html>'''
