from __future__ import annotations

"""Derived pre-action horizon, size, and selection freedom for trading.

There is no externally fixed semantic horizon, externally authored trade size,
or externally imposed semantic limit in this layer.

For a returned natural form N:

    horizon(N) = exact empirical persistence depth of the relative hair / truth
                 class into later executable returned closures;

    size(N)    = bottleneck translated capacity of the returned relative ball;

    freedom(N) = the currently witnessed joint region generated by that horizon
                 and ball, with every unwitnessed continuation preserved OPEN.

Selection freedom evolves only through returned evidence:

    F_(t+1) = Close(F_t + ReturnedFidelity_t)

Hair fidelity is measured only through exact translational-truth equality. No
epsilon, score threshold, trend, forecast, or similarity rule is introduced.
The fidelity profile at lag h asks whether an occurrence of the current truth
class at frame t is returned as the same truth class at an executable frame
t+h. The derived horizon is the longest contiguous lag prefix with perfect
observed fidelity. If there is no executable comparison, horizon remains OPEN.

Ball size is only derived when every leg of the returned closed itinerary carries
an explicitly translated relative capacity in one common unit. Raw venue quote
sizes in incomparable asset units are not silently combined. If translated
capacity is missing, size remains OPEN.

A witnessed boundary is not treated as a permanent external restriction. The
next unwitnessed continuation remains an interaction frontier. Later returns may
expand, contract, or transform the admissible region. Missing evidence never
widens the region and never gets replaced by a configured constant.
"""

from decimal import Decimal, InvalidOperation
from typing import Any, Mapping, Sequence

from .closure_continuity import OPEN_STATUS, WITNESSED_STATUS
from .trading_natural_form_closure import resolve_open_sensor_trading_closure

PROTOCOL = "closure.supernet/trading-relative-hair-horizon-ball-size-selection-freedom-v2"


def _decimal(value: Any) -> Decimal | None:
    if value is None:
        return None
    try:
        result = value if isinstance(value, Decimal) else Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError):
        return None
    return result if result.is_finite() else None


def _text(value: Decimal | None) -> str | None:
    return None if value is None else format(value, "f")


def _return_id(row: Mapping[str, Any], index: int) -> str:
    return str(row.get("return_id") or row.get("id") or f"sensor-return-{index}")


def _relation_signature(form: Mapping[str, Any]) -> tuple[tuple[str, str], ...]:
    return tuple(
        (str(row.get("source_token") or ""), str(row.get("target_token") or ""))
        for row in form.get("directed_relation_signature", [])
    )


def _truth_id(form: Mapping[str, Any]) -> str:
    return str(form.get("closure_truth_id") or form.get("closure_id") or "")


def _executable(form: Mapping[str, Any]) -> bool:
    trade = dict(form.get("trade_projection") or {})
    return (
        form.get("status") == WITNESSED_STATUS
        and trade.get("execution_return_status") == WITNESSED_STATUS
    )


def _frame_forms(
    *,
    observer_id: str | None,
    frame: Sequence[Mapping[str, Any]],
    max_returns: int | None,
) -> list[dict[str, Any]]:
    closure = resolve_open_sensor_trading_closure(
        observer_id=observer_id,
        sensor_feedback=frame,
        max_returns=max_returns,
    )
    return [
        dict(form)
        for form in closure.get("natural_forms", [])
        if form.get("status") == WITNESSED_STATUS
    ]


def derive_relative_hair_horizon(
    *,
    current_form: Mapping[str, Any],
    observer_id: str | None,
    sensor_history: Sequence[Sequence[Mapping[str, Any]]],
    max_returns: int | None = None,
) -> dict[str, Any]:
    """Derive horizon from exact hair/TT fidelity to later executable closure."""

    current_id = _truth_id(current_form)
    signature = _relation_signature(current_form)
    if not current_id or not signature or len(sensor_history) < 2:
        return {
            "status": OPEN_STATUS,
            "relative_hair_fidelity": None,
            "horizon_return_steps": None,
            "fidelity_profile": [],
            "open_reason": "INSUFFICIENT_RETURNED_HISTORY_FOR_RELATIVE_HAIR_FIDELITY",
            "fixed_horizon": None,
            "fixed_horizon_authors_truth": False,
            "derived_from_exact_translational_truth": True,
        }

    frames = [
        _frame_forms(
            observer_id=observer_id,
            frame=frame,
            max_returns=max_returns,
        )
        for frame in sensor_history
    ]
    by_frame: list[dict[tuple[tuple[str, str], ...], list[dict[str, Any]]]] = []
    for forms in frames:
        grouped: dict[tuple[tuple[str, str], ...], list[dict[str, Any]]] = {}
        for form in forms:
            grouped.setdefault(_relation_signature(form), []).append(form)
        by_frame.append(grouped)

    profile: list[dict[str, Any]] = []
    horizon = 0
    any_comparison = False
    perfect_prefix = True
    for lag in range(1, len(by_frame)):
        comparable = 0
        same_truth = 0
        for left_index in range(0, len(by_frame) - lag):
            left_forms = by_frame[left_index].get(signature, [])
            if not any(_truth_id(form) == current_id for form in left_forms):
                continue
            right_forms = [
                form
                for form in by_frame[left_index + lag].get(signature, [])
                if _executable(form)
            ]
            if not right_forms:
                continue
            comparable += 1
            if any(_truth_id(form) == current_id for form in right_forms):
                same_truth += 1
        fidelity = None if comparable == 0 else same_truth / comparable
        profile.append(
            {
                "lag_return_steps": lag,
                "comparable_occurrences": comparable,
                "same_truth_occurrences": same_truth,
                "relative_hair_fidelity": fidelity,
                "perfect_exact_fidelity": bool(comparable and same_truth == comparable),
            }
        )
        if comparable:
            any_comparison = True
            if perfect_prefix and same_truth == comparable:
                horizon = lag
            else:
                perfect_prefix = False

    if not any_comparison:
        return {
            "status": OPEN_STATUS,
            "relative_hair_fidelity": None,
            "horizon_return_steps": None,
            "fidelity_profile": profile,
            "open_reason": "NO_LATER_EXECUTABLE_CLOSURE_COMPARISON",
            "fixed_horizon": None,
            "fixed_horizon_authors_truth": False,
            "derived_from_exact_translational_truth": True,
        }

    lag_one = next(
        (row for row in profile if row["lag_return_steps"] == 1 and row["comparable_occurrences"]),
        None,
    )
    return {
        "status": WITNESSED_STATUS,
        "relative_hair_fidelity": (
            lag_one["relative_hair_fidelity"] if lag_one is not None else None
        ),
        "horizon_return_steps": horizon,
        "fidelity_profile": profile,
        "zero_horizon": horizon == 0,
        "fixed_horizon": None,
        "fixed_horizon_authors_truth": False,
        "horizon_is_derived_from_relative_hair_fidelity": True,
        "derived_from_exact_translational_truth": True,
        "similarity_tolerance_used": False,
    }


def derive_relative_ball_size(
    *,
    current_form: Mapping[str, Any],
    current_feedback: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Derive relative ball size as returned-cycle bottleneck capacity."""

    raw_by_id = {
        _return_id(row, index): dict(row)
        for index, row in enumerate(current_feedback)
    }
    return_ids = [str(value) for value in current_form.get("return_ids", [])]
    capacities: list[tuple[str, Decimal, str]] = []
    missing: list[str] = []
    for return_id in return_ids:
        row = raw_by_id.get(return_id)
        if row is None:
            missing.append(return_id)
            continue
        raw_value = None
        for key in (
            "relative_ball_size",
            "relative_size",
            "executable_relative_size",
            "relative_capacity",
            "translated_size",
        ):
            if row.get(key) is not None:
                raw_value = row.get(key)
                break
        value = _decimal(raw_value)
        unit = str(row.get("relative_size_unit") or row.get("capacity_unit") or "")
        if value is None or value < 0 or not unit:
            missing.append(return_id)
            continue
        capacities.append((return_id, value, unit))

    units = {unit for _, _, unit in capacities}
    if missing or len(capacities) != len(return_ids) or len(units) != 1:
        return {
            "status": OPEN_STATUS,
            "relative_ball_size": None,
            "unit": next(iter(units)) if len(units) == 1 else None,
            "missing_or_incomparable_return_ids": missing,
            "open_reason": (
                "RELATIVE_BALL_CAPACITY_MUST_BE_RETURNED_IN_ONE_TRANSLATED_UNIT"
            ),
            "raw_quote_size_is_not_silently_a_relative_ball_size": True,
            "external_position_size_authors_action": False,
        }

    bottleneck_id, bottleneck, unit = min(capacities, key=lambda item: item[1])
    return {
        "status": WITNESSED_STATUS,
        "relative_ball_size": _text(bottleneck),
        "unit": unit,
        "bottleneck_return_id": bottleneck_id,
        "leg_capacities": [
            {"return_id": return_id, "relative_capacity": _text(value), "unit": edge_unit}
            for return_id, value, edge_unit in capacities
        ],
        "size_is_relative_ball_bottleneck": True,
        "external_position_size_authors_action": False,
    }


def _previous_matching_form(
    *,
    current_form: Mapping[str, Any],
    observer_id: str | None,
    sensor_history: Sequence[Sequence[Mapping[str, Any]]],
    max_returns: int | None,
) -> dict[str, Any] | None:
    if len(sensor_history) < 2:
        return None
    previous_forms = _frame_forms(
        observer_id=observer_id,
        frame=sensor_history[-2],
        max_returns=max_returns,
    )
    truth_id = _truth_id(current_form)
    for form in previous_forms:
        if truth_id and _truth_id(form) == truth_id:
            return form
    signature = _relation_signature(current_form)
    for form in previous_forms:
        if signature and _relation_signature(form) == signature:
            return form
    return None


def _temporal_frontier(horizon: Mapping[str, Any]) -> dict[str, Any]:
    if horizon.get("status") != WITNESSED_STATUS:
        return {
            "status": OPEN_STATUS,
            "kind": "RETURN_RELATIVE_HAIR_FIDELITY",
            "next_return_step": None,
            "reason": horizon.get("open_reason") or "TEMPORAL_SELECTION_FREEDOM_UNWITNESSED",
        }
    steps = int(horizon.get("horizon_return_steps") or 0)
    next_step = steps + 1
    profile = [dict(row) for row in horizon.get("fidelity_profile", [])]
    next_row = next(
        (row for row in profile if int(row.get("lag_return_steps") or 0) == next_step),
        None,
    )
    if (
        next_row is not None
        and int(next_row.get("comparable_occurrences") or 0) > 0
        and next_row.get("perfect_exact_fidelity") is False
    ):
        return {
            "status": WITNESSED_STATUS,
            "kind": "EXACT_RELATIVE_HAIR_FIDELITY_BREAK",
            "next_return_step": next_step,
            "comparison": next_row,
            "boundary_is_empirically_identified": True,
        }
    return {
        "status": OPEN_STATUS,
        "kind": "RETURN_NEXT_RELATIVE_HAIR_CONTINUATION",
        "next_return_step": next_step,
        "reason": "NEXT_TEMPORAL_CONTINUATION_NOT_YET_RETURNED",
        "boundary_is_empirically_identified": False,
    }


def _ball_frontier(size: Mapping[str, Any]) -> dict[str, Any]:
    if size.get("status") != WITNESSED_STATUS:
        return {
            "status": OPEN_STATUS,
            "kind": "RETURN_RELATIVE_BALL_CAPACITY",
            "current_upper_bound": None,
            "unit": size.get("unit"),
            "reason": size.get("open_reason") or "BALL_SELECTION_FREEDOM_UNWITNESSED",
        }
    return {
        "status": OPEN_STATUS,
        "kind": "RETURN_LARGER_RELATIVE_BALL_IF_AVAILABLE",
        "current_upper_bound": size.get("relative_ball_size"),
        "unit": size.get("unit"),
        "reason": "CAPACITY_BEYOND_RETURNED_BALL_REMAINS_OPEN",
        "current_boundary_is_returned": True,
    }


def _freedom_evolution(
    *,
    current_horizon: Mapping[str, Any],
    current_size: Mapping[str, Any],
    previous_horizon: Mapping[str, Any] | None,
    previous_size: Mapping[str, Any] | None,
) -> dict[str, Any]:
    if previous_horizon is None or previous_size is None:
        return {
            "status": OPEN_STATUS,
            "state": "INITIAL_OR_UNCOMPARABLE_RETURNED_REGION",
            "temporal_change": None,
            "ball_change": None,
        }

    temporal_change: str | None = None
    if (
        current_horizon.get("status") == WITNESSED_STATUS
        and previous_horizon.get("status") == WITNESSED_STATUS
    ):
        current_steps = int(current_horizon.get("horizon_return_steps") or 0)
        previous_steps = int(previous_horizon.get("horizon_return_steps") or 0)
        temporal_change = (
            "EXPANDED" if current_steps > previous_steps
            else "CONTRACTED" if current_steps < previous_steps
            else "STABLE"
        )
    elif current_horizon.get("status") == WITNESSED_STATUS:
        temporal_change = "EXPANDED_FROM_OPEN"
    elif previous_horizon.get("status") == WITNESSED_STATUS:
        temporal_change = "CONTRACTED_TO_OPEN"

    ball_change: str | None = None
    current_ball = _decimal(current_size.get("relative_ball_size"))
    previous_ball = _decimal(previous_size.get("relative_ball_size"))
    current_unit = current_size.get("unit")
    previous_unit = previous_size.get("unit")
    if (
        current_size.get("status") == WITNESSED_STATUS
        and previous_size.get("status") == WITNESSED_STATUS
        and current_ball is not None
        and previous_ball is not None
        and current_unit == previous_unit
    ):
        ball_change = (
            "EXPANDED" if current_ball > previous_ball
            else "CONTRACTED" if current_ball < previous_ball
            else "STABLE"
        )
    elif current_size.get("status") == WITNESSED_STATUS and previous_size.get("status") != WITNESSED_STATUS:
        ball_change = "EXPANDED_FROM_OPEN"
    elif previous_size.get("status") == WITNESSED_STATUS and current_size.get("status") != WITNESSED_STATUS:
        ball_change = "CONTRACTED_TO_OPEN"

    changes = {change for change in (temporal_change, ball_change) if change is not None}
    if not changes:
        state = "OPEN"
        status = OPEN_STATUS
    elif changes <= {"STABLE"}:
        state = "STABLE"
        status = WITNESSED_STATUS
    elif not any(change.startswith("CONTRACTED") for change in changes):
        state = "EXPANDED"
        status = WITNESSED_STATUS
    elif not any(change.startswith("EXPANDED") for change in changes):
        state = "CONTRACTED"
        status = WITNESSED_STATUS
    else:
        state = "TRANSFORMED"
        status = WITNESSED_STATUS

    return {
        "status": status,
        "state": state,
        "temporal_change": temporal_change,
        "ball_change": ball_change,
        "external_limit_caused_change": False,
        "returned_evidence_caused_change": True,
    }


def derive_selection_freedom(
    *,
    current_form: Mapping[str, Any],
    observer_id: str | None,
    current_feedback: Sequence[Mapping[str, Any]],
    sensor_history: Sequence[Sequence[Mapping[str, Any]]] = (),
    relative_hair_horizon: Mapping[str, Any] | None = None,
    relative_ball_size: Mapping[str, Any] | None = None,
    max_returns: int | None = None,
) -> dict[str, Any]:
    """Close the currently admissible selection region from returned evidence."""

    horizon = dict(relative_hair_horizon or derive_relative_hair_horizon(
        current_form=current_form,
        observer_id=observer_id,
        sensor_history=sensor_history,
        max_returns=max_returns,
    ))
    size = dict(relative_ball_size or derive_relative_ball_size(
        current_form=current_form,
        current_feedback=current_feedback,
    ))

    horizon_witnessed = horizon.get("status") == WITNESSED_STATUS
    size_witnessed = size.get("status") == WITNESSED_STATUS
    horizon_steps = int(horizon.get("horizon_return_steps") or 0) if horizon_witnessed else None
    ball_value = _decimal(size.get("relative_ball_size")) if size_witnessed else None
    executable_region_witnessed = bool(
        horizon_witnessed
        and size_witnessed
        and horizon_steps is not None
        and horizon_steps > 0
        and ball_value is not None
        and ball_value > 0
    )

    previous_form = _previous_matching_form(
        current_form=current_form,
        observer_id=observer_id,
        sensor_history=sensor_history,
        max_returns=max_returns,
    )
    previous_horizon: dict[str, Any] | None = None
    previous_size: dict[str, Any] | None = None
    if previous_form is not None:
        previous_horizon = derive_relative_hair_horizon(
            current_form=previous_form,
            observer_id=observer_id,
            sensor_history=sensor_history[:-1],
            max_returns=max_returns,
        )
        previous_size = derive_relative_ball_size(
            current_form=previous_form,
            current_feedback=sensor_history[-2],
        )

    temporal_frontier = _temporal_frontier(horizon)
    ball_frontier = _ball_frontier(size)
    evolution = _freedom_evolution(
        current_horizon=horizon,
        current_size=size,
        previous_horizon=previous_horizon,
        previous_size=previous_size,
    )
    status = WITNESSED_STATUS if horizon_witnessed and size_witnessed else OPEN_STATUS
    remaining_open_frontiers = [
        frontier
        for frontier in (temporal_frontier, ball_frontier)
        if frontier.get("status") == OPEN_STATUS
    ]

    return {
        "status": status,
        "closure_id": current_form.get("closure_id"),
        "closure_truth_id": current_form.get("closure_truth_id"),
        "equation": "F_(t+1)=Close(F_t + ReturnedFidelity_t)",
        "temporal_freedom": {
            "status": horizon.get("status"),
            "lower_exclusive_return_steps": 0 if horizon_witnessed else None,
            "upper_inclusive_return_steps": horizon_steps,
            "derived_from_relative_hair_fidelity": True,
            "frontier": temporal_frontier,
        },
        "ball_freedom": {
            "status": size.get("status"),
            "lower_exclusive": "0" if size_witnessed else None,
            "upper_inclusive": size.get("relative_ball_size"),
            "unit": size.get("unit"),
            "derived_from_relative_ball": True,
            "frontier": ball_frontier,
        },
        "executable_region_witnessed": executable_region_witnessed,
        "empty_action_region": bool(status == WITNESSED_STATUS and not executable_region_witnessed),
        "evolution": evolution,
        "remaining_open_frontiers": remaining_open_frontiers,
        "remaining_open_frontier_count": len(remaining_open_frontiers),
        "selection_freedom_from_returned_closure": True,
        "selection_freedom_evolves_over_time_and_fidelity": True,
        "external_limit_authors_selection": False,
        "configured_threshold_authors_selection": False,
        "missing_evidence_widens_selection": False,
        "unwitnessed_boundary_remains_open": True,
        "open_frontier_can_be_resolved_by_later_return": True,
    }


def derive_preaction_relative_coordinates(
    *,
    observer_id: str | None,
    natural_closure: Mapping[str, Any],
    current_feedback: Sequence[Mapping[str, Any]],
    sensor_history: Sequence[Sequence[Mapping[str, Any]]] = (),
    max_returns: int | None = None,
) -> dict[str, Any]:
    """Derive horizon, size, and selection freedom before action."""

    by_closure_id: dict[str, dict[str, Any]] = {}
    rows: list[dict[str, Any]] = []
    for raw in natural_closure.get("natural_forms", []):
        form = dict(raw)
        closure_id = str(form.get("closure_id") or form.get("closure_truth_id") or "")
        if not closure_id:
            continue
        horizon = derive_relative_hair_horizon(
            current_form=form,
            observer_id=observer_id,
            sensor_history=sensor_history,
            max_returns=max_returns,
        )
        size = derive_relative_ball_size(
            current_form=form,
            current_feedback=current_feedback,
        )
        freedom = derive_selection_freedom(
            current_form=form,
            observer_id=observer_id,
            current_feedback=current_feedback,
            sensor_history=sensor_history,
            relative_hair_horizon=horizon,
            relative_ball_size=size,
            max_returns=max_returns,
        )
        coordinates = {
            "closure_id": closure_id,
            "relative_hair_horizon": horizon,
            "relative_ball_size": size,
            "selection_freedom": freedom,
            "horizon_from_relative_hair_fidelity": True,
            "size_from_relative_ball": True,
            "selection_freedom_from_returned_fidelity": True,
            "derived_before_action": True,
        }
        by_closure_id[closure_id] = coordinates
        rows.append(coordinates)

    return {
        "protocol": PROTOCOL,
        "equation": (
            "H(N)=exact relative-hair fidelity depth into later executable closure; "
            "Size(N)=bottleneck translated capacity of the relative ball; "
            "F_(t+1)=Close(F_t + ReturnedFidelity_t)"
        ),
        "forms": rows,
        "by_closure_id": by_closure_id,
        "horizon_from_relative_hair_fidelity": True,
        "size_from_relative_ball": True,
        "selection_freedom_from_returned_fidelity": True,
        "selection_freedom_evolves_over_time_and_fidelity": True,
        "remaining_limits_are_open_selection_frontiers": True,
        "unwitnessed_boundary_remains_open": True,
        "external_limit_authors_selection": False,
        "configured_threshold_authors_selection": False,
        "fixed_horizon_present": False,
        "external_position_size_present": False,
        "derived_before_action": True,
    }


__all__ = [
    "PROTOCOL",
    "derive_preaction_relative_coordinates",
    "derive_relative_ball_size",
    "derive_relative_hair_horizon",
    "derive_selection_freedom",
]
