from __future__ import annotations

"""Natural trading closure generated by open sensor-feedback hair equations.

The runtime never defines a trade as ``ask_t -> bid_(t+1)`` and never selects a
horizon, signal, or strategy before closure. Source-preserving sensor returns
supply directed hair equations. Their returned graph induces local ball
partitions; a directed return through that maze witnesses a local closure.

For each witnessed local closure:

* the signed unitary curvature is the natural-form cost;
* its magnitude is the amplitude projection;
* the returned ball path is the timing projection;
* signal and trade are simultaneous relative projections of the same
  translation, not sequential semantic layers.

The numerical readings may differ. Their equality is equality of translation
identity, not equality as scalars.
"""

from collections import deque
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
import hashlib
import json
from typing import Any, Iterable, Mapping, Sequence

from .closure_continuity import (
    OPEN_STATUS,
    WITNESSED_STATUS,
    computation_boundary_open,
    unique_strings,
)
from .interactive_derivation_calculus import (
    REFUTED_STATUS,
    loop_refutation_certificate,
    translation_certificate,
)

PROTOCOL = "closure.supernet/open-sensor-trading-natural-form-nrrf868-869-v1"


def _stable(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )


def _digest(prefix: str, value: Any) -> str:
    return f"{prefix}:{hashlib.sha256(_stable(value).encode('utf-8')).hexdigest()[:24]}"


def _decimal(value: Any, *, field: str) -> Decimal:
    try:
        result = value if isinstance(value, Decimal) else Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError) as exc:
        raise ValueError(f"{field} must be a finite decimal") from exc
    if not result.is_finite():
        raise ValueError(f"{field} must be a finite decimal")
    return result


def _text(value: Decimal | None) -> str | None:
    return None if value is None else format(value, "f")


def _first(value: Mapping[str, Any], *keys: str) -> Any:
    for key in keys:
        if key in value and value[key] is not None:
            return value[key]
    return None


def _source_ids(value: Mapping[str, Any]) -> list[str]:
    raw = _first(
        value,
        "source_return_ids",
        "source_ids",
        "exact_source_ids",
    )
    if raw is None:
        raw = []
    if isinstance(raw, str):
        raw = [raw]
    return unique_strings(raw)


def _timestamp(value: Any) -> datetime | None:
    if value is None:
        return None
    raw = str(value).strip()
    if not raw:
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _bounded_prefix(
    values: Sequence[Mapping[str, Any]],
    *,
    limit: int | None,
) -> tuple[list[Mapping[str, Any]], list[Mapping[str, Any]], dict[str, Any] | None]:
    if limit is None:
        return list(values), [], None
    normalized = max(0, int(limit))
    selected = list(values[:normalized])
    remainder = list(values[normalized:])
    boundary = None
    if remainder:
        boundary = computation_boundary_open(
            boundary="OPEN_SENSOR_TRADING_RETURN_LIMIT",
            configured_limit=normalized,
            observed=len(values),
        )
    return selected, remainder, boundary


def _normalize_return(index: int, raw: Mapping[str, Any]) -> dict[str, Any]:
    item = dict(raw)
    return_id = str(_first(item, "return_id", "id") or f"sensor-return-{index}")
    source = str(
        _first(
            item,
            "source_token",
            "source_node",
            "from_token",
            "from",
            "source",
        )
        or ""
    )
    target = str(
        _first(
            item,
            "target_token",
            "target_node",
            "to_token",
            "to",
            "target",
        )
        or ""
    )
    source_ids = _source_ids(item)
    returned = item.get("returned") is True or item.get("witnessed") is True
    if "returned" not in item and "witnessed" not in item:
        returned = bool(source_ids)

    parse_error: str | None = None
    relation_value: Decimal | None
    hair_delta: Decimal | None
    natural_value: Decimal | None
    try:
        relation_value = _decimal(
            _first(
                item,
                "relation_value",
                "relative_value",
                "observed_value",
                "total_cost",
                "cost",
                "value",
            ),
            field="relation_value",
        )
        explicit_hair_delta = _first(item, "hair_delta", "potential_delta")
        if explicit_hair_delta is not None:
            hair_delta = _decimal(explicit_hair_delta, field="hair_delta")
        else:
            hair_source = _first(item, "hair_source", "source_potential")
            hair_target = _first(item, "hair_target", "target_potential")
            if hair_source is None and hair_target is None:
                hair_delta = Decimal("0")
            elif hair_source is None or hair_target is None:
                raise ValueError(
                    "hair_source and hair_target must be supplied together"
                )
            else:
                hair_delta = _decimal(
                    hair_target,
                    field="hair_target",
                ) - _decimal(hair_source, field="hair_source")
        natural_value = relation_value - hair_delta
    except ValueError as exc:
        relation_value = None
        hair_delta = None
        natural_value = None
        parse_error = str(exc)

    source_preserved = bool(source and target and source_ids and returned)
    cost_complete = item.get("cost_complete") is True
    authenticated = item.get("authenticated") is True
    valid = bool(source_preserved and parse_error is None)

    return {
        "index": index,
        "return_id": return_id,
        "source_token": source or None,
        "target_token": target or None,
        "source_ids": source_ids,
        "returned": returned,
        "source_preserved": source_preserved,
        "authenticated": authenticated,
        "cost_complete": cost_complete,
        "relation_value": _text(relation_value),
        "hair_delta": _text(hair_delta),
        "natural_form_value": _text(natural_value),
        "timestamp": _first(item, "timestamp", "observed_at", "returned_at"),
        "parse_error": parse_error,
        "status": WITNESSED_STATUS if valid else OPEN_STATUS,
        "successor_quote_used": False,
        "fixed_horizon_used": False,
        "feature_selector_used": False,
    }


def _components(edges: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    members = sorted(
        {
            str(endpoint)
            for edge in edges
            for endpoint in (edge.get("source_token"), edge.get("target_token"))
            if endpoint
        }
    )
    parent = {member: member for member in members}

    def find(item: str) -> str:
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(left: str, right: str) -> None:
        lroot, rroot = find(left), find(right)
        if lroot != rroot:
            parent[rroot] = lroot

    for edge in edges:
        if edge.get("status") != WITNESSED_STATUS:
            continue
        left = str(edge["source_token"])
        right = str(edge["target_token"])
        union(left, right)

    groups: dict[str, list[str]] = {}
    for member in members:
        groups.setdefault(find(member), []).append(member)

    rows: list[dict[str, Any]] = []
    for group in sorted((sorted(value) for value in groups.values())):
        body = {"member_tokens": group}
        rows.append(
            {
                "ball_id": _digest("trading-ball", body),
                "member_tokens": group,
                "partition_is_return_generated": True,
                "partition_label_authors_truth": False,
            }
        )
    return rows


def _find_path(
    adjacency: Mapping[str, Sequence[dict[str, Any]]],
    start: str,
    goal: str,
) -> list[dict[str, Any]] | None:
    if start == goal:
        return []
    queue: deque[tuple[str, list[dict[str, Any]]]] = deque([(start, [])])
    visited = {start}
    while queue:
        node, path = queue.popleft()
        for edge in adjacency.get(node, ()):
            target = str(edge["target_token"])
            next_path = [*path, edge]
            if target == goal:
                return next_path
            if target not in visited:
                visited.add(target)
                queue.append((target, next_path))
    return None


def _ball_id_for(tokens: Iterable[str], balls: Sequence[Mapping[str, Any]]) -> str | None:
    token_set = set(tokens)
    for ball in balls:
        if token_set.issubset(set(map(str, ball.get("member_tokens", [])))):
            return str(ball["ball_id"])
    return None


def _duration_projection(edges: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    indices = [int(edge["index"]) for edge in edges]
    parsed = [
        parsed
        for edge in edges
        if (parsed := _timestamp(edge.get("timestamp"))) is not None
    ]
    opened_at = min(parsed).isoformat() if parsed else None
    closed_at = max(parsed).isoformat() if parsed else None
    duration_seconds = (
        _text(Decimal(str((max(parsed) - min(parsed)).total_seconds())))
        if len(parsed) >= 2
        else None
    )
    return {
        "maze_return_ids": [str(edge["return_id"]) for edge in edges],
        "maze_steps": len(edges),
        "support_start_index": min(indices),
        "support_end_index": max(indices),
        "opened_at": opened_at,
        "closed_at": closed_at,
        "duration_seconds": duration_seconds,
        "fixed_horizon": None,
        "timing_is_ball_partition_projection": True,
    }


def _cycle_row(
    *,
    observer_id: str,
    edges: Sequence[dict[str, Any]],
    balls: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    edge_ids = [str(edge["return_id"]) for edge in edges]
    token_path = [str(edges[0]["source_token"])] + [
        str(edge["target_token"]) for edge in edges
    ]
    members = sorted(set(token_path))
    ball_id = _ball_id_for(members, balls)
    translation_id = _digest(
        "trading-closure-translation",
        {
            "observer_id": observer_id,
            "ball_id": ball_id,
            "return_ids": edge_ids,
        },
    )
    relation_sum = sum(
        (_decimal(edge["relation_value"], field="relation_value") for edge in edges),
        Decimal("0"),
    )
    hair_sum = sum(
        (_decimal(edge["hair_delta"], field="hair_delta") for edge in edges),
        Decimal("0"),
    )
    curvature = sum(
        (
            _decimal(edge["natural_form_value"], field="natural_form_value")
            for edge in edges
        ),
        Decimal("0"),
    )
    hair_closed = hair_sum == 0
    natural_profit = -curvature
    amplitude = abs(curvature)
    source_ids = unique_strings(
        source_id
        for edge in edges
        for source_id in edge.get("source_ids", [])
    )
    source_witnessed = bool(observer_id and ball_id and source_ids)
    closure_witnessed = bool(source_witnessed and hair_closed)
    closure_status = WITNESSED_STATUS if closure_witnessed else OPEN_STATUS

    if closure_witnessed and curvature == 0:
        calculus_status = WITNESSED_STATUS
        derivation_certificate = translation_certificate(
            observer_id=observer_id,
            source_id=token_path[0],
            target_id=token_path[-1],
            relation_id=translation_id,
            source_return_ids=source_ids,
        )
        loop_refutation = None
    elif closure_witnessed:
        calculus_status = REFUTED_STATUS
        derivation_certificate = None
        loop_refutation = loop_refutation_certificate(
            observer_id=observer_id,
            source_id=token_path[0],
            target_id=token_path[-1],
            relation_id=translation_id,
            source_return_ids=source_ids,
            loop_witness={
                "return_ids": edge_ids,
                "token_path": token_path,
                "unitary_curvature": _text(curvature),
                "natural_profit": _text(natural_profit),
                "ball_id": ball_id,
            },
        )
    else:
        calculus_status = OPEN_STATUS
        derivation_certificate = None
        loop_refutation = None

    if natural_profit > 0:
        orientation = "PROFITABLE"
    elif natural_profit < 0:
        orientation = "COSTLY"
    else:
        orientation = "FLAT"

    timing = _duration_projection(edges)
    timing["translation_id"] = translation_id
    amplitude_projection = {
        "translation_id": translation_id,
        "unitary_curvature": _text(curvature),
        "amplitude": _text(amplitude),
        "amplitude_is_unitary_curvature_projection": True,
    }
    all_authenticated = all(edge.get("authenticated") is True for edge in edges)
    all_cost_complete = all(edge.get("cost_complete") is True for edge in edges)
    execution_return_witnessed = bool(all_authenticated and all_cost_complete)
    signal = {
        "projection": "RELATIVE_SIGNAL",
        "translation_id": translation_id,
        "ball_id": ball_id,
        "orientation": orientation,
        "amplitude": _text(amplitude),
        "natural_profit": _text(natural_profit),
        "status": closure_status,
    }
    trade = {
        "projection": "RELATIVE_TRADE",
        "translation_id": translation_id,
        "ball_id": ball_id,
        "orientation": orientation,
        "amplitude": _text(amplitude),
        "natural_profit": _text(natural_profit),
        "status": closure_status,
        "execution_return_status": (
            WITNESSED_STATUS if execution_return_witnessed else OPEN_STATUS
        ),
        "admissible": bool(
            closure_witnessed
            and natural_profit > 0
            and execution_return_witnessed
        ),
        "automatic_order_submission": False,
    }

    return {
        "closure_id": translation_id,
        "status": closure_status,
        "ball_id": ball_id,
        "return_ids": edge_ids,
        "token_path": token_path,
        "source_ids": source_ids,
        "relation_sum": _text(relation_sum),
        "hair_sum": _text(hair_sum),
        "hair_closes_on_return": hair_closed,
        "unitary_curvature": _text(curvature),
        "natural_profit": _text(natural_profit),
        "amplitude": _text(amplitude),
        "orientation": orientation,
        "timing": timing,
        "amplitude_projection": amplitude_projection,
        "signal_projection": signal,
        "trade_projection": trade,
        "amplitude_timing_translation_equal": (
            amplitude_projection["translation_id"] == timing["translation_id"]
        ),
        "signal_trade_translation_equal": (
            signal["translation_id"] == trade["translation_id"]
        ),
        "amplitude_timing_numerically_identical": False,
        "signal_precedes_trade_semantically": False,
        "trade_precedes_signal_semantically": False,
        "zero_curvature_calculus_status": calculus_status,
        "translation_witness": derivation_certificate,
        "loop_refutation": loop_refutation,
        "existence_witnessed_by_nonzero_curvature": bool(
            closure_witnessed and curvature != 0
        ),
        "continuation_status": OPEN_STATUS,
        "open_reasons": [
            reason
            for condition, reason in (
                (bool(observer_id), "MISSING_RELATIVE_OBSERVER"),
                (bool(ball_id), "BALL_PARTITION_NOT_DERIVED"),
                (bool(source_ids), "MISSING_SOURCE_RETURN"),
                (hair_closed, "HAIR_EQUATIONS_DO_NOT_CLOSE"),
            )
            if not condition
        ],
    }


def resolve_open_sensor_trading_closure(
    *,
    observer_id: str | None,
    sensor_feedback: Sequence[Mapping[str, Any]],
    max_returns: int | None = None,
) -> dict[str, Any]:
    """Resolve natural trading forms from an open returned sensor continuum.

    Every item is one returned directed relation with a total relation value and
    an optional hair equation. Ball partitions come from source-preserving
    connectivity. A natural form appears only when the returned maze itself
    closes a directed itinerary. No successor observation, duration, size,
    strategy, or feature threshold is selected by the kernel.
    """

    observer = str(observer_id or "")
    selected, remainder, boundary = _bounded_prefix(
        sensor_feedback,
        limit=max_returns,
    )
    returns = [_normalize_return(index, raw) for index, raw in enumerate(selected)]
    witnessed_edges = [
        row for row in returns if row["status"] == WITNESSED_STATUS
    ]
    balls = _components(witnessed_edges)

    adjacency: dict[str, list[dict[str, Any]]] = {}
    cycles: list[dict[str, Any]] = []
    cycle_signatures: set[str] = set()
    for edge in witnessed_edges:
        source = str(edge["source_token"])
        target = str(edge["target_token"])
        returning_path = _find_path(adjacency, target, source)
        if returning_path is not None:
            cycle_edges = [edge, *returning_path]
            signature = _stable([item["return_id"] for item in cycle_edges])
            if signature not in cycle_signatures:
                cycle_signatures.add(signature)
                cycles.append(
                    _cycle_row(
                        observer_id=observer,
                        edges=cycle_edges,
                        balls=balls,
                    )
                )
        adjacency.setdefault(source, []).append(edge)

    cycle_returns = {
        return_id
        for cycle in cycles
        for return_id in cycle["return_ids"]
    }
    open_balls = [
        {
            **ball,
            "status": OPEN_STATUS,
            "open_reason": "NO_RETURNED_DIRECTED_CLOSURE_YET",
        }
        for ball in balls
        if not any(
            edge["return_id"] in cycle_returns
            and (
                edge["source_token"] in ball["member_tokens"]
                or edge["target_token"] in ball["member_tokens"]
            )
            for edge in witnessed_edges
        )
    ]
    relation_coordinates = sorted(
        {
            (str(edge["source_token"]), str(edge["target_token"]))
            for edge in witnessed_edges
        }
    )
    witnessed_cycles = [
        cycle for cycle in cycles if cycle["status"] == WITNESSED_STATUS
    ]
    status = (
        WITNESSED_STATUS
        if observer and witnessed_cycles and not remainder
        else OPEN_STATUS
    )
    body: dict[str, Any] = {
        "protocol": PROTOCOL,
        "equation": (
            "sensor returns -> hair equations -> returned ball partition -> "
            "unitary curvature = natural form; amplitude~timing and signal~trade "
            "through one translation"
        ),
        "status": status,
        "observer_id": observer or None,
        "sensor_returns": returns,
        "unprocessed_sensor_returns": [dict(item) for item in remainder],
        "ball_partition": balls,
        "open_balls": open_balls,
        "natural_forms": cycles,
        "witnessed_natural_form_count": len(witnessed_cycles),
        "relation_coordinates": [
            {"source_token": source, "target_token": target}
            for source, target in relation_coordinates
        ],
        "continuum_dimension": len(relation_coordinates),
        "relational_closure_continuum": True,
        "relation_form_truth_translation_same_continuum": True,
        "profit_is_local_reading_of_global_cost_closure": True,
        "unitary_curvature_gives_amplitude": True,
        "ball_partition_maze_gives_timing": True,
        "amplitude_timing_are_relative_translations": True,
        "signal_trade_are_relative_translations": True,
        "ask_to_immediately_succeeding_bid_is_definition": False,
        "successor_observation_authors_closure": False,
        "fixed_horizon": None,
        "horizon_is_semantic": False,
        "feature_selection_is_semantic": False,
        "strategy_selection_is_semantic": False,
        "route_nomination_authors_truth": False,
        "configuration_authors_truth": False,
        "computation_bounds_author_truth": False,
        "automatic_order_submission": False,
        "existence_closed": False,
        "dialectic_continuation_status": OPEN_STATUS,
    }
    if boundary is not None:
        body["boundary_receipt"] = boundary
    body["id"] = _digest("open-sensor-trading-closure", body)
    return body


__all__ = ["PROTOCOL", "resolve_open_sensor_trading_closure"]
